// data.js - Generated from user list

const HOTEL = {
  "lat": 37.5626699,
  "lng": 126.9906379
};

const DISTRICTS = {
  "mapo": {
    "nameCN": "麻浦區",
    "nameKR": "마포구"
  },
  "jongno": {
    "nameCN": "鐘路區",
    "nameKR": "종로구"
  },
  "jung": {
    "nameCN": "中區",
    "nameKR": "중구"
  },
  "yongsan": {
    "nameCN": "龍山區",
    "nameKR": "용산구"
  },
  "gangnam": {
    "nameCN": "江南區",
    "nameKR": "강남구"
  },
  "seongdong": {
    "nameCN": "城東區",
    "nameKR": "성동구"
  },
  "dongdaemun": {
    "nameCN": "東大門區",
    "nameKR": "동대문구"
  },
  "seodaemun": {
    "nameCN": "西大門區",
    "nameKR": "서대문구"
  },
  "seocho": {
    "nameCN": "瑞草區",
    "nameKR": "서초구"
  },
  "yeongdeungpo": {
    "nameCN": "永登浦區",
    "nameKR": "영등포구"
  },
  "eunpyeong": {
    "nameCN": "恩平區",
    "nameKR": "은평구"
  },
  "nowon": {
    "nameCN": "蘆原區",
    "nameKR": "노원구"
  },
  "seongbuk": {
    "nameCN": "城北區",
    "nameKR": "성북구"
  },
  "gwangjin": {
    "nameCN": "廣津區",
    "nameKR": "광진구"
  },
  "songpa": {
    "nameCN": "松坡區",
    "nameKR": "송파구"
  },
  "gangseo": {
    "nameCN": "江西區",
    "nameKR": "강서구"
  }
};

const CATEGORY_COLORS = {
  "漂亮咖": "var(--cat-cafe)",
  "點心": "var(--cat-snack)",
  "韓式鹹食": "var(--cat-korean)",
  "義大利麵": "var(--cat-pasta)",
  "烤肉": "var(--cat-bbq)",
  "暖暖ㄉ湯": "var(--cat-soup)",
  "湯飯": "var(--cat-gukbap)",
  "麵": "var(--cat-noodle)",
  "HOTEL": "var(--cat-hotel)"
};

const RESTAURANTS = [
  {
    "id": "r_1",
    "district": "seodaemun",
    "nameCN": "日記",
    "nameKR": "일기",
    "lat": 37.5652633080296,
    "lng": 126.92318197854732,
    "category": "漂亮咖",
    "hashtags": [],
    "googleRating": "5.0",
    "googleReviews": "7份",
    "IGreels": "",
    "featuredDish": "法式吐司",
    "addressEN": "18 Seongmisan-ro 29an-gil, Yeonnam-dong, Seoul",
    "dongKR": "연희동",
    "dongEN": "Yeonhui-dong",
    "naverUrl": "https://map.naver.com/p/entry/place/1072280224?placePath=%2Fhome",
    "googleUrl": "https://maps.app.goo.gl/qcx7TZZzVZ2MqsKW6"
  },
  {
    "id": "r_2",
    "district": "mapo",
    "nameCN": "Tis Snack Bar",
    "nameKR": "티스 스낵바",
    "lat": 37.56000611449929,
    "lng": 126.92639656323402,
    "category": "漂亮咖",
    "hashtags": [],
    "googleRating": "4.3",
    "googleReviews": "12份",
    "IGreels": "",
    "featuredDish": null,
    "addressEN": "7 Yeonhui-ro, Donggyo-dong, Mapo-gu, Seoul",
    "dongKR": "연남동",
    "dongEN": "Yeonnam-dong",
    "naverUrl": "https://naver.me/FHlg8V6n",
    "googleUrl": "https://maps.app.goo.gl/2YCd5PGVzKx9wFCV7"
  },
  {
    "id": "r_3",
    "district": "jongno",
    "nameCN": "乙支餃子",
    "nameKR": "을지만두",
    "lat": 37.567799785243054,
    "lng": 127.00816192379439,
    "category": "點心",
    "hashtags": [
      "鳥屎推薦",
      "豆沙包"
    ],
    "googleRating": "4.7",
    "googleReviews": "103份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "18-95 Euljiro 6(yuk)-ga, Jung District, Seoul",
    "dongKR": "종로5·6가동",
    "dongEN": "Jongno5·6Gadong",
    "naverUrl": "https://naver.me/IgJC0bG9",
    "googleUrl": "https://maps.app.goo.gl/njU5cS99CNp7fpTt8"
  },
  {
    "id": "r_4",
    "district": "jongno",
    "nameCN": "Garlic Boy",
    "nameKR": "갈릭보이",
    "lat": 37.57029654438751,
    "lng": 126.99870004874413,
    "category": "點心",
    "hashtags": [
      "廣藏市場",
      "麵包"
    ],
    "googleRating": "4.5",
    "googleReviews": "181份",
    "featuredDish": "大蒜麵包",
    "IGreels": "",
    "addressEN": "88 Changgyeonggung-ro, Jongno District, Seoul",
    "dongKR": "종로1·2·3·4가동",
    "dongEN": "Jongno1·2·3·4Gadong",
    "naverUrl": "https://naver.me/GALWeZId",
    "googleUrl": "https://maps.app.goo.gl/W3HokNVdmZ4s9Qmk6"
  },
  {
    "id": "r_6",
    "district": "jongno",
    "nameCN": "Abebe Bakery",
    "nameKR": "아베베베이커리",
    "lat": 37.56963000154928,
    "lng": 126.99993613470386,
    "category": "點心",
    "hashtags": [
      "廣藏市場",
      "麵包"
    ],
    "googleRating": "4.4",
    "googleReviews": "365份",
    "featuredDish": "濟州島來的奶油餡甜甜圈（口味頗多）、橘子氣泡飲",
    "IGreels": "",
    "addressEN": "201 Cheonggyecheon-ro, Jongno District, Seoul",
    "dongKR": "종로1·2·3·4가동",
    "dongEN": "Jongno1·2·3·4Gadong",
    "naverUrl": "https://naver.me/Fmf6KIKT",
    "googleUrl": "https://maps.app.goo.gl/DbQtUMocZ8zjGPpp8"
  },
  {
    "id": "r_7",
    "district": "jongno",
    "nameCN": "廣藏糖餅",
    "nameKR": "광장호떡",
    "lat": 37.570712825870885,
    "lng": 127.00050463281508,
    "category": "點心",
    "hashtags": [
      "廣藏市場",
      "糖餅"
    ],
    "googleRating": "4.4",
    "googleReviews": "46份",
    "featuredDish": "蜂蜜、紅豆、起司",
    "IGreels": "",
    "addressEN": "206 Jong-ro, Jongno 5(o)-ga, Jongno District, Seoul",
    "dongKR": "종로5·6가동",
    "dongEN": "Jongno5·6Gadong",
    "naverUrl": "https://naver.me/xl0Dyxqh",
    "googleUrl": "https://maps.app.goo.gl/Q3x8Sq4sBiJsnRtLA"
  },
  {
    "id": "r_8",
    "district": "jongno",
    "nameCN": "廣藏市場糯米麻花捲",
    "nameKR": "광장시장 찹쌀꽈배기",
    "lat": 37.570696279743174,
    "lng": 127.00020584217398,
    "category": "點心",
    "hashtags": [
      "廣藏市場",
      "麻花捲"
    ],
    "googleRating": "4.5",
    "googleReviews": "757份",
    "featuredDish": "糯米麻花、紅豆甜甜圈、黑米糯米甜甜圈、紅豆糯米甜甜圈",
    "IGreels": "",
    "addressEN": "Seoul, Jongno District, Jongno 4(sa)-ga, 188 105호",
    "dongKR": "종로1·2·3·4가동",
    "dongEN": "Jongno1·2·3·4Gadong",
    "naverUrl": "https://naver.me/5tJt5fE9",
    "googleUrl": "https://maps.app.goo.gl/RWB73w7MNdHpo7Mz8"
  },
  {
    "id": "r_9",
    "district": "seongdong",
    "nameCN": "自然島鹽可頌",
    "nameKR": "자연도소금빵",
    "lat": 37.54240883178305,
    "lng": 127.05535314769233,
    "category": "點心",
    "hashtags": [
      "麵包"
    ],
    "googleRating": "4.3",
    "googleReviews": "800份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "56-1 Yeonmujang-gil, Seongdong-gu, Seoul",
    "dongKR": "성수2가3동",
    "dongEN": "Seongsu 2(i)-ga 3(sam)-dong",
    "naverUrl": "https://naver.me/xUw1qmBE",
    "googleUrl": "https://maps.app.goo.gl/NWxkVnHBQkBXcMjP9"
  },
  {
    "id": "r_10",
    "district": "mapo",
    "nameCN": "自然島鹽可頌",
    "nameKR": "자연도소금빵",
    "lat": 37.55971179779057,
    "lng": 126.92435372523332,
    "category": "點心",
    "hashtags": [
      "麵包"
    ],
    "googleRating": "4.3",
    "googleReviews": "218份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "Seoul, Mapo-gu, Yanghwa-ro 21-gil, 33 1 층",
    "dongKR": "연남동",
    "dongEN": "Yeonnam-dong",
    "naverUrl": "https://naver.me/xjgchnQq",
    "googleUrl": "https://maps.app.goo.gl/aV4skhkNznWoWsqs9"
  },
  {
    "id": "r_11",
    "district": "seongdong",
    "nameCN": "Hanib Bagel",
    "nameKR": "한입베이글",
    "lat": 37.541446375269956,
    "lng": 127.04626120257495,
    "category": "點心",
    "hashtags": [
      "麵包"
    ],
    "googleRating": "4.7",
    "googleReviews": "86份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "317 Ttukseom-ro, Seongdong-gu, Seoul",
    "dongKR": "성수1가1동",
    "dongEN": "Seongsu1(il)-ga1(il)-dong",
    "naverUrl": "https://naver.me/GFB1Amu6",
    "googleUrl": "https://maps.app.goo.gl/vvvT5J8fgstHgs6t6"
  },
  {
    "id": "r_13",
    "district": "mapo",
    "nameCN": "雨耳樂",
    "nameKR": "우이락 망원본점",
    "lat": 37.556462775781085,
    "lng": 126.90594519964782,
    "category": "點心",
    "hashtags": [
      "望遠市場",
      "炸辣椒"
    ],
    "googleRating": "4.7",
    "googleReviews": "853份",
    "IGreels": "https://www.instagram.com/reel/DVOgpLtj5Y-/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "featuredDish": "辣椒鑲肉（一份三支，原味、起司、甜辣、清湯口味）",
    "addressEN": "22 Poeun-ro 8-gil, Mapo-gu, Seoul",
    "dongKR": "망원2동",
    "dongEN": "Mangwon 2(i)-dong",
    "naverUrl": "https://naver.me/FgHD8wDh",
    "googleUrl": "https://maps.app.goo.gl/1qDmjVNh29sAkvv48"
  },
  {
    "id": "r_14",
    "district": "mapo",
    "nameCN": "勳勳糖餅",
    "nameKR": "훈훈호떡",
    "lat": 37.55593850138689,
    "lng": 126.9063636809724,
    "category": "點心",
    "hashtags": [
      "望遠市場",
      "糖餅"
    ],
    "googleRating": "4.5",
    "googleReviews": "193份",
    "IGreels": "https://www.instagram.com/reel/DVOgpLtj5Y-/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "featuredDish": "原味、起司粉、黃豆粉、Oreo、堅果、冰淇淋口味",
    "addressEN": "25 Poeun-ro 6-gil, Mapo-gu, Seoul",
    "dongKR": "망원2동",
    "dongEN": "Mangwon 2(i)-dong",
    "naverUrl": "https://naver.me/F74V29Yu",
    "googleUrl": "https://maps.app.goo.gl/VJNDTukWhWNmYQwd9"
  },
  {
    "id": "r_15",
    "district": "seongdong",
    "nameCN": "韓貞仙",
    "nameKR": "한정선",
    "lat": 37.54288729937332,
    "lng": 127.0541684849995,
    "category": "點心",
    "hashtags": [
      "大福"
    ],
    "googleRating": "4.4",
    "googleReviews": "301份",
    "IGreels": "",
    "featuredDish": "杜拜巧克力、巧克力草莓、紅豆草莓、艾草紅豆草莓、紅豆奶油、橘子、柿子、奇異果、麝香葡萄、鳳梨口味",
    "addressEN": "Seoul, Seongdong-gu, Yeonmujang-gil, 43 1 1F",
    "dongKR": "성수2가3동",
    "dongEN": "Seongsu 2(i)-ga 3(sam)-dong",
    "naverUrl": "https://naver.me/F9N46G4y",
    "googleUrl": "https://maps.app.goo.gl/45zvnBgxbVrWsynS7"
  },
  {
    "id": "r_16",
    "district": "seongdong",
    "nameCN": "Le Freak",
    "nameKR": "르프리크",
    "lat": 37.54453794817913,
    "lng": 127.0526830592445,
    "category": "點心",
    "hashtags": [
      "漢堡"
    ],
    "googleRating": "4.5",
    "googleReviews": "412份",
    "featuredDish": "炸雞漢堡",
    "IGreels": "",
    "addressEN": "Seoul, Seongdong-gu, Yeonmujang 5-gil, 9-16 B103호",
    "dongKR": "성수1가2동",
    "dongEN": "Seongsu1(il)-ga2(i)-dong",
    "naverUrl": "https://naver.me/GwpMNYi5",
    "googleUrl": "https://maps.app.goo.gl/QixbjBwPqRUs9DsRA"
  },
  {
    "id": "r_17",
    "district": "jung",
    "nameCN": "萬培阿里郎菜包肉",
    "nameKR": "만배아리랑보쌈",
    "lat": 37.54917400626818,
    "lng": 126.86244184613925,
    "category": "韓式鹹食",
    "hashtags": [
      "白切肉"
    ],
    "googleRating": "4.6",
    "googleReviews": "61份",
    "IGreels": "https://www.instagram.com/reel/DXQliiHE2VZ/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "featuredDish": "豬頸背肉泡菜包飯、海鮮蛤蠣刀削麵",
    "addressEN": "17 Deungchon-ro 51-gil, Gangseo-gu, Seoul",
    "dongKR": "등촌2동",
    "dongEN": "Deungchon 2(i)-dong",
    "naverUrl": "https://naver.me/GG7tTMkh",
    "googleUrl": "https://maps.app.goo.gl/YcB3qwxnmxSyJob97"
  },
  {
    "id": "r_18",
    "district": "yongsan",
    "nameCN": "高豆里",
    "nameKR": "고두리",
    "lat": 37.53142959619399,
    "lng": 126.96883337019365,
    "category": "韓式鹹食",
    "hashtags": [
      "豆腐料理"
    ],
    "googleRating": "4.4",
    "googleReviews": "65份",
    "IGreels": "",
    "featuredDish": "芝麻葉豆腐煎餅、辣豆腐湯、泡菜烤五花肉、豆腐鍋",
    "addressEN": "Seoul, Yongsan District, Hangangno 2(i)-ga, 2-39 1층",
    "dongKR": "원효로1동",
    "dongEN": "Wonhyoro1-dong",
    "naverUrl": "https://naver.me/Gj6X2WEN",
    "googleUrl": "https://maps.app.goo.gl/Wh25SX1iDHUfh1WM6"
  },
  {
    "id": "r_19",
    "district": "mapo",
    "nameCN": "QS炸雞",
    "nameKR": "큐스닭강정",
    "lat": 37.55633423473403,
    "lng": 126.90623677945798,
    "category": "韓式鹹食",
    "hashtags": [
      "望遠市場",
      "炸雞"
    ],
    "googleRating": "3.4",
    "googleReviews": "118份",
    "IGreels": "https://www.instagram.com/reel/DVOgpLtj5Y-/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "featuredDish": "",
    "addressEN": "27 Mangwon-ro 8-gil, Mangwon-dong, Mapo-gu, Seoul",
    "dongKR": "망원2동",
    "dongEN": "Mangwon 2(i)-dong",
    "naverUrl": "https://naver.me/5eUc0fjc",
    "googleUrl": "https://maps.app.goo.gl/quzzUH3HXh8AtnZT6"
  },
  {
    "id": "r_20",
    "district": "jongno",
    "nameCN": "元祖裸飯捲",
    "nameKR": "원조누드치즈김밥",
    "lat": 37.570532822281315,
    "lng": 126.99881861506704,
    "category": "韓式鹹食",
    "hashtags": [
      "廣藏市場",
      "飯卷"
    ],
    "googleRating": "4.3",
    "googleReviews": "642份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "41호, 3-2 Changgyeonggung-ro 12-gil, Jongno District, Seoul",
    "dongKR": "종로1·2·3·4가동",
    "dongEN": "Jongno1·2·3·4Gadong",
    "naverUrl": "https://naver.me/xDJucSNM",
    "googleUrl": "https://maps.app.goo.gl/1rkcsQUrCfZ5nQuQ8"
  },
  {
    "id": "r_22",
    "district": "mapo",
    "nameCN": "申美京弘大辣炒雞排",
    "nameKR": "신미경 홍대닭갈비",
    "lat": 37.552353714735695,
    "lng": 126.92188976323828,
    "category": "韓式鹹食",
    "hashtags": [
      "蕭芝芹說一定要吃到的辣炒雞"
    ],
    "googleRating": "4.6",
    "googleReviews": "1618份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "31-10 Wausan-ro 21-gil, Mapo-gu, Seoul",
    "dongKR": "서교동",
    "dongEN": "Seogyo-dong",
    "naverUrl": "https://naver.me/Gubw0jFk",
    "googleUrl": "https://maps.app.goo.gl/GKEh4CGQ4WqPfdKm8"
  },
  {
    "id": "r_23",
    "district": "mapo",
    "nameCN": "韓式馬鈴薯丸湯",
    "nameKR": "옹시미",
    "lat": 37.558829775544446,
    "lng": 126.92207282660203,
    "category": "韓式鹹食",
    "hashtags": [
      "蕎麥煎餅",
      "馬鈴薯疙瘩"
    ],
    "googleRating": "4.8",
    "googleReviews": "79份",
    "IGreels": "https://www.instagram.com/reel/DWgS1xskQFM/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "featuredDish": "",
    "addressEN": "Seoul, Mapo-gu, World Cup buk-ro 4-gil, 59 1층",
    "dongKR": "연남동",
    "dongEN": "Yeonnam-dong",
    "naverUrl": "https://naver.me/xv3DN2qg",
    "googleUrl": "https://maps.app.goo.gl/mxJxER2iPTrQAWqZA"
  },
  {
    "id": "r_24",
    "district": "jung",
    "nameCN": "豬腳小姐",
    "nameKR": "미쓰족발",
    "lat": 37.56480447041299,
    "lng": 126.98343479153587,
    "category": "韓式鹹食",
    "hashtags": [
      "豬腳"
    ],
    "googleRating": "4.4",
    "googleReviews": "1264份",
    "featuredDish": "",
    "IGreels": "https://www.instagram.com/reel/DQy70fmExU-/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "addressEN": "21 Myeongdong 3-gil, Jung District, Seoul",
    "dongKR": "명동",
    "dongEN": "Myeong-dong",
    "naverUrl": "https://naver.me/xv3DIjyN",
    "googleUrl": "https://maps.app.goo.gl/vGJZcKVpbngnKHgL7"
  },
  {
    "id": "r_25",
    "district": "mapo",
    "nameCN": "豬腳小姐",
    "nameKR": "미쓰족발",
    "lat": 37.55583068170859,
    "lng": 126.92366110267096,
    "category": "韓式鹹食",
    "hashtags": [
      "豬腳"
    ],
    "googleRating": "4.3",
    "googleReviews": "1989份",
    "featuredDish": "",
    "IGreels": "https://www.instagram.com/reel/DQy70fmExU-/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "addressEN": "123-1 Eoulmadang-ro, Mapo-gu, Seoul",
    "dongKR": "서교동",
    "dongEN": "Seogyo-dong",
    "naverUrl": "https://naver.me/GubwlgWD",
    "googleUrl": "https://maps.app.goo.gl/4NVDJYZqHBb7pXPx7"
  },
  {
    "id": "r_26",
    "district": "jongno",
    "nameCN": "Solsot Pot Rice",
    "nameKR": "솔솥",
    "lat": 37.57437972166945,
    "lng": 126.99017356672171,
    "category": "韓式鹹食",
    "hashtags": [
      "釜飯"
    ],
    "googleRating": "4.5",
    "googleReviews": "474份",
    "IGreels": "",
    "featuredDish": "牛排、鰻魚",
    "addressEN": "1층, 46 Samil-daero 30-gil, Jongno District, Seoul",
    "dongKR": "가회동",
    "dongEN": "Gahoe-dong",
    "naverUrl": "https://naver.me/FjbnsEfv",
    "googleUrl": "https://maps.app.goo.gl/zLdiWCDsC9Ln5CPH7"
  },
  {
    "id": "r_27",
    "district": "seongbuk",
    "nameCN": "八百家",
    "nameKR": "팔백집",
    "lat": 37.58655069729023,
    "lng": 127.02980144517065,
    "category": "韓式鹹食",
    "hashtags": [
      "排骨"
    ],
    "googleRating": "4.2",
    "googleReviews": "59份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "3 Jongam-ro 27-gil, 고려대 Seongbuk District, Seoul",
    "dongKR": "안암동",
    "dongEN": "Anamdong",
    "naverUrl": "https://naver.me/G1wSXB6K",
    "googleUrl": "https://maps.app.goo.gl/X8M9pWiJEnvx5gKn7"
  },
  {
    "id": "r_28",
    "district": "mapo",
    "nameCN": "Hey George",
    "nameKR": "헤이죠지",
    "lat": 37.561696333045596,
    "lng": 126.92656609845942,
    "category": "義大利麵",
    "hashtags": [],
    "googleRating": "4.9",
    "googleReviews": "291份",
    "IGreels": "https://www.instagram.com/reel/DWBkFyiE9C6/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "featuredDish": "",
    "addressEN": "383-96 Yeonnam-dong, Mapo-gu, Seoul",
    "dongKR": "연남동",
    "dongEN": "Yeonnam-dong",
    "naverUrl": "https://naver.me/GHvqnvW2",
    "googleUrl": "https://maps.app.goo.gl/xXsKiwxEdGZHvyM18"
  },
  {
    "id": "r_29",
    "district": "mapo",
    "nameCN": "HAVE",
    "nameKR": "해브 연남파스타",
    "lat": 37.5618752803497,
    "lng": 126.92605047035961,
    "category": "義大利麵",
    "hashtags": [],
    "googleRating": "4.7",
    "googleReviews": "43份",
    "IGreels": "",
    "featuredDish": "生鮭魚、生牛肉冷義大利麵",
    "addressEN": "55 Yeonhui-ro 1-gil, Mapo-gu, Seoul",
    "dongKR": "연남동",
    "dongEN": "Yeonnam-dong",
    "naverUrl": "https://naver.me/5chutspQ",
    "googleUrl": "https://maps.app.goo.gl/3Ho8kTM728YQ5dFf6"
  },
  {
    "id": "r_30",
    "district": "jung",
    "nameCN": "文化食堂",
    "nameKR": "문화식당",
    "lat": 37.5657210007695,
    "lng": 127.01993758400434,
    "category": "義大利麵",
    "hashtags": [],
    "googleRating": "4.5",
    "googleReviews": "35份",
    "IGreels": "",
    "featuredDish": "蛋包飯、三合一義大利麵",
    "addressEN": "Seoul, Jung District, Sindang-dong, 140-3 2층",
    "dongKR": "황학동",
    "dongEN": "Hwanghak-dong",
    "naverUrl": "https://naver.me/GoD7vP4W",
    "googleUrl": "https://maps.app.goo.gl/wnydzvHpSMATqhH76"
  },
  {
    "id": "r_31",
    "district": "mapo",
    "nameCN": "兔子停",
    "nameKR": "토끼정",
    "lat": 37.55197218154435,
    "lng": 126.9206657690827,
    "category": "義大利麵",
    "hashtags": [],
    "googleRating": "4.3",
    "googleReviews": "269份",
    "IGreels": "https://www.instagram.com/reel/DXBwkXqSq_t/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "featuredDish": "奶油咖哩烏龍麵、炸豬排",
    "addressEN": "13 Jandari-ro 2-gil, Mapo-gu, Seoul",
    "dongKR": "서교동",
    "dongEN": "Seogyo-dong",
    "naverUrl": "https://naver.me/xAFC52uD",
    "googleUrl": "https://maps.app.goo.gl/MZ2pKyuFvmPzhzAP8"
  },
  {
    "id": "r_32",
    "district": "jung",
    "nameCN": "兔子停",
    "nameKR": "토끼정",
    "lat": 37.5553073483632,
    "lng": 126.97102122363017,
    "category": "義大利麵",
    "hashtags": [],
    "googleRating": "3.7",
    "googleReviews": "999份",
    "IGreels": "https://www.instagram.com/reel/DXBwkXqSq_t/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "featuredDish": "奶油咖哩烏龍麵、炸豬排",
    "addressEN": "405 Hangang-daero, Jung District, Seoul",
    "dongKR": "중림동",
    "dongEN": "Jungnim-dong",
    "naverUrl": "https://naver.me/IgJGrH7I",
    "googleUrl": "https://maps.app.goo.gl/9d6ZD83cmPPgokGd7"
  },
  {
    "id": "r_33",
    "district": "mapo",
    "nameCN": "Hotel De GGOODD",
    "nameKR": "오뗄드꾸뜨",
    "lat": 37.56295092968078,
    "lng": 126.92528693833093,
    "category": "義大利麵",
    "hashtags": [],
    "googleRating": "4.7",
    "googleReviews": "318份",
    "IGreels": "",
    "featuredDish": "蜂蜜培根玫瑰醬、法式吐司",
    "addressEN": "Seoul, Mapo-gu, Donggyo-ro 46-gil, 7 101호",
    "dongKR": "연남동",
    "dongEN": "Yeonnam-dong",
    "naverUrl": "https://naver.me/Fr7p5RtM",
    "googleUrl": "https://maps.app.goo.gl/ifjp2xV2Reoyu8pS9"
  },
  {
    "id": "r_34",
    "district": "mapo",
    "nameCN": "十分三文魚",
    "nameKR": "연어롭다",
    "lat": 37.56121742295383,
    "lng": 126.92571412992987,
    "category": "義大利麵",
    "hashtags": [],
    "googleRating": "4.3",
    "googleReviews": "150份",
    "IGreels": "",
    "featuredDish": "鮭魚刺身",
    "addressEN": "42 Donggyo-ro 38-gil, Mapo-gu, Seoul",
    "dongKR": "연남동",
    "dongEN": "Yeonnam-dong",
    "naverUrl": "https://naver.me/G9r5qDkF",
    "googleUrl": "https://maps.app.goo.gl/ie8jg29kZhVj79rD7"
  },
  {
    "id": "r_35",
    "district": "mapo",
    "nameCN": "麻浦牛小腸城",
    "nameKR": "마포곱창타운",
    "lat": 37.55951194234785,
    "lng": 126.92269792610809,
    "category": "烤肉",
    "hashtags": [
      "烤腸"
    ],
    "googleRating": "4.7",
    "googleReviews": "2334份",
    "IGreels": "https://www.instagram.com/reel/DWJhii_kmMQ/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "addressEN": "20 Donggyo-ro 27-gil, Mapo-gu, Seoul",
    "dongKR": "연남동",
    "dongEN": "Yeonnam-dong",
    "naverUrl": "https://naver.me/59voptcA",
    "googleUrl": "https://maps.app.goo.gl/kSGXfZRnHTaZMsLb8"
  },
  {
    "id": "r_36",
    "district": "mapo",
    "nameCN": "天使烤腸",
    "nameKR": "천사곱창",
    "lat": 37.55281129100612,
    "lng": 126.92186511023914,
    "category": "烤肉",
    "hashtags": [
      "烤腸"
    ],
    "googleRating": "4.3",
    "googleReviews": "60份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "36-4 Wausan-ro 21-gil, 서교동 Mapo-gu, Seoul",
    "dongKR": "서교동",
    "dongEN": "Seogyo-dong",
    "naverUrl": "https://map.naver.com/p/entry/place/37801100?placePath=%2Fhome",
    "googleUrl": "https://maps.app.goo.gl/wHU7eQtj2FnsbLEC7"
  },
  {
    "id": "r_37",
    "district": "mapo",
    "nameCN": "第一烤腸",
    "nameKR": "제일곱창",
    "lat": 37.55295855988006,
    "lng": 126.92233182621861,
    "category": "烤肉",
    "hashtags": [
      "烤腸"
    ],
    "googleRating": "4.9",
    "googleReviews": "405份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "Seoul, Mapo-gu, Wausan-ro 21-gil, 28-7 1층",
    "dongKR": "서교동",
    "dongEN": "Seogyo-dong",
    "naverUrl": "https://naver.me/IDFUNqBM",
    "googleUrl": "https://maps.app.goo.gl/GuiPfrY9fPK9Z514A"
  },
  {
    "id": "r_38",
    "district": "gangnam",
    "nameCN": "新沙烤牛腸",
    "nameKR": "신사소곱창",
    "lat": 37.51800331518248,
    "lng": 127.0214520703212,
    "category": "烤肉",
    "hashtags": [
      "烤腸"
    ],
    "googleRating": "4.3",
    "googleReviews": "495份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "62 Apgujeong-ro 2-gil, Gangnam District, Seoul",
    "dongKR": "신사동",
    "dongEN": "Sinsa-dong",
    "naverUrl": "https://naver.me/xucpY7ad",
    "googleUrl": "https://maps.app.goo.gl/7XpPjUUWnJ3cTJ6X9"
  },
  {
    "id": "r_39",
    "district": "mapo",
    "nameCN": "喉嚨水芹菜烤肉",
    "nameKR": "목구멍 홍대입구역점",
    "lat": 37.557077696819455,
    "lng": 126.92058925529835,
    "category": "烤肉",
    "hashtags": [
      "水芹菜"
    ],
    "googleRating": "4.5",
    "googleReviews": "341份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "Seoul, Mapo-gu, World Cup buk-ro 4-gil, 8 1층",
    "dongKR": "연남동",
    "dongEN": "Yeonnam-dong",
    "naverUrl": "https://naver.me/GUwSxgH4",
    "googleUrl": "https://maps.app.goo.gl/TPpm35Jk1eBQVk7U7"
  },
  {
    "id": "r_40",
    "district": "mapo",
    "nameCN": "The Grazing Pig",
    "nameKR": "풀뜯는돼지",
    "lat": 37.561058528933664,
    "lng": 126.92464938879996,
    "category": "烤肉",
    "hashtags": [
      "水芹菜"
    ],
    "googleRating": "4.6",
    "googleReviews": "312份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "Seoul, Mapo-gu, Donggyo-ro 32-gil, 7 1층",
    "dongKR": "연남동",
    "dongEN": "Yeonnam-dong",
    "naverUrl": "https://naver.me/GBFHNoZY",
    "googleUrl": "https://maps.app.goo.gl/bxogfTqMWeLTfC3e7"
  },
  {
    "id": "r_41",
    "district": "yongsan",
    "nameCN": "豬肉店",
    "nameKR": "도야집",
    "lat": 37.53223958160214,
    "lng": 126.97253167234624,
    "category": "烤肉",
    "hashtags": [],
    "googleRating": "4.7",
    "googleReviews": "181份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "27 Hangang-daero 52-gil, Yongsan District, Seoul",
    "dongKR": "한강로동",
    "dongEN": "Hangangnodong",
    "naverUrl": "https://naver.me/GJTiGMwx",
    "googleUrl": "https://maps.app.goo.gl/QuUmyigTZDfdfpX29"
  },
  {
    "id": "r_42",
    "district": "mapo",
    "nameCN": "朝鮮火爐",
    "nameKR": "조선화로구이",
    "lat": 37.5560490561716,
    "lng": 126.92062442072883,
    "category": "烤肉",
    "hashtags": [
      "韓牛"
    ],
    "googleRating": "4.5",
    "googleReviews": "1235份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "351-18 Seogyo-dong, Mapo-gu, Seoul",
    "dongKR": "서교동",
    "dongEN": "Seogyo-dong",
    "naverUrl": "https://naver.me/5JpU0TnJ",
    "googleUrl": "https://maps.app.goo.gl/xFojyCRadtY5bn947"
  },
  {
    "id": "r_43",
    "district": "jung",
    "nameCN": "缽山豬皮",
    "nameKR": "발산껍데기",
    "lat": 37.56029341643286,
    "lng": 126.83710523340443,
    "category": "烤肉",
    "hashtags": [
      "豬皮"
    ],
    "googleRating": "4.2",
    "googleReviews": "80份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "공항대로 269-15 1층 112호, Gangseo-gu, Seoul",
    "dongKR": "가양1동",
    "dongEN": "Gayang 1(il)-dong",
    "naverUrl": "https://naver.me/GipB4rqa",
    "googleUrl": "https://maps.app.goo.gl/9PkSxV3YfARNSxSH7"
  },
  {
    "id": "r_44",
    "district": "mapo",
    "nameCN": "肉夢",
    "nameKR": "맛집 육몽",
    "lat": 37.553600263314785,
    "lng": 126.92059782139611,
    "category": "烤肉",
    "hashtags": [],
    "googleRating": "4.8",
    "googleReviews": "3063份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "19 Yanghwa-ro 16-gil, Mapo-gu, Seoul",
    "dongKR": "서교동",
    "dongEN": "Seogyo-dong",
    "naverUrl": "https://naver.me/FY3yAWtF",
    "googleUrl": "https://maps.app.goo.gl/LJNeFxSD34YUeaZs9"
  },
  {
    "id": "r_45",
    "district": "seongdong",
    "nameCN": "黨燒肉",
    "nameKR": "꿉당",
    "lat": 37.54324343284116,
    "lng": 127.05756144714864,
    "category": "烤肉",
    "hashtags": [
      "黨燒肉"
    ],
    "googleRating": "4.5",
    "googleReviews": "449份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "Seoul, Seongdong-gu, Seongsui-ro 20-gil, 10 경협회관 104호",
    "dongKR": "성수2가3동",
    "dongEN": "Seongsu 2(i)-ga 3(sam)-dong",
    "naverUrl": "https://naver.me/FZ275oxv",
    "googleUrl": "https://maps.app.goo.gl/eGNPJ8WD931LjteY6"
  },
  {
    "id": "r_46",
    "district": "seocho",
    "nameCN": "黨燒肉",
    "nameKR": "꿉당",
    "lat": 37.516848649162775,
    "lng": 127.01908852436736,
    "category": "烤肉",
    "hashtags": [
      "黨燒肉"
    ],
    "googleRating": "4.4",
    "googleReviews": "769份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "615 Gangnam-daero, Seocho District, Seoul",
    "dongKR": "잠원동",
    "dongEN": "Jamwon-dong",
    "naverUrl": "https://naver.me/5uIYjvee",
    "googleUrl": "https://maps.app.goo.gl/c6ErZdNr2ZSEUTMv8"
  },
  {
    "id": "r_47",
    "district": "seongdong",
    "nameCN": "祖傳三代馬鈴薯排骨湯",
    "nameKR": "소문난 성수 감자탕",
    "lat": 37.5430457083058,
    "lng": 127.05438584606846,
    "category": "暖暖ㄉ湯",
    "hashtags": [
      "馬鈴薯排骨湯"
    ],
    "googleRating": "4.1",
    "googleReviews": "6035份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "45 Yeonmujang-gil, Seongdong-gu, Seoul",
    "dongKR": "성수2가3동",
    "dongEN": "Seongsu 2(i)-ga 3(sam)-dong",
    "naverUrl": "https://naver.me/GgWkGs9y",
    "googleUrl": "https://maps.app.goo.gl/pcuNTtNQERyY4BYRA"
  },
  {
    "id": "r_48",
    "district": "mapo",
    "nameCN": "百年土種蔘鷄湯",
    "nameKR": "백년토종삼계탕",
    "lat": 37.554471739672366,
    "lng": 126.92022646413989,
    "category": "暖暖ㄉ湯",
    "hashtags": [
      "人蔘雞湯"
    ],
    "googleRating": "4.2",
    "googleReviews": "1921份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "118 Yanghwa-ro, Mapo-gu, Seoul",
    "dongKR": "서교동",
    "dongEN": "Seogyo-dong",
    "naverUrl": "https://naver.me/53lKjV6q",
    "googleUrl": "https://maps.app.goo.gl/HpVQmDBfZC1JJbvL7"
  },
  {
    "id": "r_49",
    "district": "mapo",
    "nameCN": "光雞",
    "nameKR": "광계",
    "lat": 37.56177028796768,
    "lng": 126.92631117840976,
    "category": "暖暖ㄉ湯",
    "hashtags": [
      "人蔘雞湯"
    ],
    "googleRating": "4.8",
    "googleReviews": "25份",
    "IGreels": "https://www.instagram.com/reel/DWLiWlmEYTS/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "featuredDish": "",
    "addressEN": "Seoul, Mapo-gu, Yeonnam-dong, 383-72 1.5층",
    "dongKR": "연남동",
    "dongEN": "Yeonnam-dong",
    "naverUrl": "https://naver.me/FgTz17PI",
    "googleUrl": "https://maps.app.goo.gl/ScX3zgs8BmunzBFg6"
  },
  {
    "id": "r_50",
    "district": "mapo",
    "nameCN": "崔社長家的雞",
    "nameKR": "최사장네닭",
    "lat": 37.56072629367486,
    "lng": 126.9237654935975,
    "category": "暖暖ㄉ湯",
    "hashtags": [
      "辣燉雞湯"
    ],
    "googleRating": "4.0",
    "googleReviews": "263份",
    "IGreels": "https://www.instagram.com/reel/DYgYyRYSJyc/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "featuredDish": "",
    "addressEN": "4-1 Yeonnam-ro, Mapo-gu, Seoul",
    "dongKR": "연남동",
    "dongEN": "Yeonnam-dong",
    "naverUrl": "https://naver.me/xWTnmRpq",
    "googleUrl": "https://maps.app.goo.gl/RhGDEncxyc1gjAn7A"
  },
  {
    "id": "r_51",
    "district": "jongno",
    "nameCN": "HOISIK",
    "nameKR": "호이식",
    "lat": 37.578281392104785,
    "lng": 126.98627126071804,
    "category": "暖暖ㄉ湯",
    "hashtags": [
      "一隻雞"
    ],
    "googleRating": "4.7",
    "googleReviews": "57份",
    "IGreels": "https://www.instagram.com/reel/DVayjKqk4kN/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "featuredDish": "",
    "addressEN": "Seoul, Jongno District, Bukchon-ro 2-gil, 10 1층",
    "dongKR": "가회동",
    "dongEN": "Gahoe-dong",
    "naverUrl": "https://naver.me/5r3E0IpQ",
    "googleUrl": "https://maps.app.goo.gl/6JTsFEwkrRkVEn617"
  },
  {
    "id": "r_52",
    "district": "jongno",
    "nameCN": "李福姬解酒湯",
    "nameKR": "이복희해장",
    "lat": 37.56941897451093,
    "lng": 126.98734439388396,
    "category": "暖暖ㄉ湯",
    "hashtags": [
      "解酒湯"
    ],
    "googleRating": "4.1",
    "googleReviews": "16份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "Seoul, Jongno District, Samil-daero, 385 이복희해장 1층, 2층",
    "dongKR": "종로1·2·3·4가동",
    "dongEN": "Jongno1·2·3·4Gadong",
    "naverUrl": "https://naver.me/5yWRkr3V",
    "googleUrl": "https://maps.app.goo.gl/BWMnH6TGkusEXe7n9"
  },
  {
    "id": "r_53",
    "district": "seongdong",
    "nameCN": "實費屋",
    "nameKR": "실비옥",
    "lat": 37.54385251524655,
    "lng": 127.05827977710037,
    "category": "暖暖ㄉ湯",
    "hashtags": [
      "牛肉海帶鍋"
    ],
    "googleRating": "4.1",
    "googleReviews": "21份",
    "featuredDish": "",
    "IGreels": "https://www.instagram.com/reel/DU5nQ7eEeZR/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "addressEN": "126 Achasan-ro, Seongdong-gu, Seoul",
    "dongKR": "성수2가3동",
    "dongEN": "Seongsu 2(i)-ga 3(sam)-dong",
    "naverUrl": "https://naver.me/GEXUrqqw",
    "googleUrl": "https://maps.app.goo.gl/ECTZ5W5x6KVahWkD6"
  },
  {
    "id": "r_54",
    "district": "jung",
    "nameCN": "保承會館",
    "nameKR": "보승회관",
    "lat": 37.56469137039903,
    "lng": 126.98479766189318,
    "category": "湯飯",
    "hashtags": [],
    "googleRating": "3.6",
    "googleReviews": "136份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "13 Myeongdong 9-gil, Jung District, Seoul",
    "dongKR": "명동",
    "dongEN": "Myeong-dong",
    "naverUrl": "https://naver.me/FfeYK0QT",
    "googleUrl": "https://maps.app.goo.gl/uZ8KizqGuHsoAJbw9"
  },
  {
    "id": "r_55",
    "district": "seodaemun",
    "nameCN": "保承會館",
    "nameKR": "보승회관",
    "lat": 37.556711016411484,
    "lng": 126.92883223394712,
    "category": "湯飯",
    "hashtags": [],
    "googleRating": "4.0",
    "googleReviews": "460份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "131 Eoulmadang-ro, Mapo-gu, Seoul",
    "dongKR": "서교동",
    "dongEN": "Seogyo-dong",
    "naverUrl": "https://naver.me/5hua5O6V",
    "googleUrl": "https://maps.app.goo.gl/ofUeBpq2YVf4pUdv8"
  },
  {
    "id": "r_56",
    "district": "jung",
    "nameCN": "河東津",
    "nameKR": "하동진",
    "lat": 37.566193664499615,
    "lng": 127.01594020597531,
    "category": "湯飯",
    "hashtags": [
      "白切肉"
    ],
    "googleRating": "4.3",
    "googleReviews": "365份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "112 Heungin-dong, Jung District, Seoul",
    "dongKR": "신당동",
    "dongEN": "Sindang-dong",
    "naverUrl": "https://naver.me/5mI0v3oy",
    "googleUrl": "https://maps.app.goo.gl/yQtUb1JLcF2dTm579"
  },
  {
    "id": "r_57",
    "district": "seongdong",
    "nameCN": "豚骨藥房",
    "nameKR": "돈골약방",
    "lat": 37.54545144642206,
    "lng": 127.05145933281165,
    "category": "湯飯",
    "hashtags": [],
    "googleRating": "4.9",
    "googleReviews": "80份",
    "IGreels": "https://www.instagram.com/reel/DYrBH8dyqSe/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "featuredDish": "",
    "addressEN": "Seoul, Seongdong-gu, Seongsuil-ro 8-gil, 28 1 층",
    "dongKR": "성수1가2동",
    "dongEN": "Seongsu1(il)-ga2(i)-dong",
    "naverUrl": "https://naver.me/GEXhVhza",
    "googleUrl": "https://maps.app.goo.gl/RyJb4Ebtcuw6BV2W9"
  },
  {
    "id": "r_58",
    "district": "jung",
    "nameCN": "正雅閣",
    "nameKR": "정아각",
    "lat": 37.64200573234901,
    "lng": 127.02476431495127,
    "category": "麵",
    "hashtags": [
      "炸醬麵"
    ],
    "googleRating": "4.3",
    "googleReviews": "60份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "1064 Hancheon-ro, Suyu-dong, Gangbuk-gu, Seoul",
    "dongKR": "수유2동",
    "dongEN": "Suyu 2(i)-dong",
    "naverUrl": "https://naver.me/502MeDkZ",
    "googleUrl": "https://maps.app.goo.gl/NoN42cFC1nCo1hjA9"
  },
  {
    "id": "r_59",
    "district": "mapo",
    "nameCN": "棒槌手工刀削麵",
    "nameKR": "",
    "lat": 37.55650575159846,
    "lng": 126.90689462815595,
    "category": "麵",
    "hashtags": [
      "望遠市場",
      "刀削麵"
    ],
    "googleRating": "4.2",
    "googleReviews": "353份",
    "IGreels": "https://www.instagram.com/reel/DUdMPfEjPSy/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "featuredDish": "",
    "addressEN": "414-26 망원제1동 Mapo-gu, Seoul",
    "dongKR": "망원2동",
    "dongEN": "Mangwon 2(i)-dong",
    "naverUrl": "https://naver.me/xv3DRVNF",
    "googleUrl": "https://maps.app.goo.gl/XW68RDME2CgpUmYT8"
  },
  {
    "id": "r_60",
    "district": "seongdong",
    "nameCN": "熊甲刀削麵",
    "nameKR": "웅칼",
    "lat": 37.545067662672174,
    "lng": 127.05424101856917,
    "category": "麵",
    "hashtags": [
      "刀削麵"
    ],
    "googleRating": "4.9",
    "googleReviews": "193份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "1F Seongdong-gu, Seongsu-dong 2(i)-ga, Achasan-ro, 92",
    "dongKR": "성수2가3동",
    "dongEN": "Seongsu 2(i)-ga 3(sam)-dong",
    "naverUrl": "https://naver.me/GcKx1wIb",
    "googleUrl": "https://maps.app.goo.gl/f71tYBxru4xTdqqm8"
  },
  {
    "id": "r_61",
    "district": "jongno",
    "nameCN": "南浦麵屋",
    "nameKR": "남포면옥",
    "lat": 37.56763265353615,
    "lng": 126.98183606824426,
    "category": "麵",
    "hashtags": [
      "冷麵"
    ],
    "googleRating": "3.8",
    "googleReviews": "2266份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "24 Eulji-ro 3-gil, Jung District, Seoul",
    "dongKR": "종로1·2·3·4가동",
    "dongEN": "Jongno1·2·3·4Gadong",
    "naverUrl": "https://naver.me/FeXRk4zh",
    "googleUrl": "https://maps.app.goo.gl/TaynxDh59wBS9TXr9"
  },
  {
    "id": "r_62",
    "district": "jongno",
    "nameCN": "乙密臺平壤冷麵",
    "nameKR": "을밀대",
    "lat": 37.567373065273685,
    "lng": 126.9800304015735,
    "category": "麵",
    "hashtags": [
      "冷麵"
    ],
    "googleRating": "4.1",
    "googleReviews": "253份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "40 B1 Namdaemun-ro 9-gil, Jung District, Seoul",
    "dongKR": "종로1·2·3·4가동",
    "dongEN": "Jongno1·2·3·4Gadong",
    "naverUrl": "https://naver.me/xrSQd4FI",
    "googleUrl": "https://maps.app.goo.gl/bSNEYm71eNAfw2Qj7"
  },
  {
    "id": "r_63",
    "district": "gangnam",
    "nameCN": "乙密臺平壤冷麵",
    "nameKR": "을밀대",
    "lat": 37.49558831128396,
    "lng": 127.03050931465313,
    "category": "麵",
    "hashtags": [
      "冷麵"
    ],
    "googleRating": "4.0",
    "googleReviews": "1442份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "46 Teheran-ro 4-gil, Gangnam District, Seoul",
    "dongKR": "역삼1동",
    "dongEN": "Yeoksam 1(il)-dong",
    "naverUrl": "https://naver.me/GYC97lmL",
    "googleUrl": "https://maps.app.goo.gl/rPV8ZdhQsdSxpNZv5"
  },
  {
    "id": "r_64",
    "district": "gangnam",
    "nameCN": "新沙煎餅",
    "nameKR": "신사전",
    "lat": 37.51884931162439,
    "lng": 127.02304408715368,
    "category": "韓式鹹食",
    "hashtags": [
      "煎餅"
    ],
    "googleRating": "4.0",
    "googleReviews": "514份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "18 Dosan-daero 11-gil, Gangnam District, Seoul",
    "dongKR": "신사동",
    "dongEN": "Sinsa-dong",
    "naverUrl": "https://naver.me/5D8tuw8q",
    "googleUrl": "https://maps.app.goo.gl/tE678JgnK2fSfhYcA"
  },
  {
    "id": "r_65",
    "district": "mapo",
    "nameCN": "Musoe泡菜五花肉",
    "nameKR": "무쇠김치삼겹",
    "lat": 37.552857615564534,
    "lng": 126.92266826736592,
    "category": "烤肉",
    "hashtags": [
      "烤腸"
    ],
    "googleRating": "4.6",
    "googleReviews": "263份",
    "featuredDish": "",
    "IGreels": "https://www.instagram.com/reel/DUc-yZ-Ep6W/?utm_source=ig_web_copy_link&igsh=NTc4MTIwNjQ2YQ==",
    "addressEN": "20-5 Wausan-ro 21-gil, Seogyo-dong, Mapo-gu, Seoul",
    "dongKR": "서교동",
    "dongEN": "Seogyo-dong",
    "naverUrl": "https://naver.me/5vcHkgA4",
    "googleUrl": "https://maps.app.goo.gl/u6fon2Hd4DzTUy7A7"
  },
  {
    "id": "r_66",
    "district": "jung",
    "nameCN": "Musoe泡菜五花肉",
    "nameKR": "무쇠김치삼겹",
    "lat": 37.56196141283083,
    "lng": 126.98537061349127,
    "category": "烤肉",
    "hashtags": [
      "烤腸"
    ],
    "googleRating": "4.8",
    "googleReviews": "988份",
    "featuredDish": "",
    "IGreels": "https://www.instagram.com/reel/DUc-yZ-Ep6W/?utm_source=ig_web_copy_link&igsh=NTc4MTIwNjQ2YQ==",
    "addressEN": "Seoul, Jung District, Myeongdong 8ga-gil, 7 2층",
    "dongKR": "명동",
    "dongEN": "Myeong-dong",
    "naverUrl": "https://naver.me/FqWta5qP",
    "googleUrl": "https://maps.app.goo.gl/uYHUuBScu5SBRJ7Z8"
  },
  {
    "id": "r_67",
    "district": "seongdong",
    "nameCN": "朝朝刀削麵",
    "nameKR": "조조칼국수",
    "lat": 37.54546414325718,
    "lng": 127.0570752631429,
    "category": "麵",
    "hashtags": [
      "蕭芝芹說一定要吃到的蛤蜊刀削麵"
    ],
    "googleRating": "4.5",
    "googleReviews": "406份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "Seoul, Seongdong-gu, Seongsuil-ro 8-gil, 55 1 층",
    "dongKR": "성수2가3동",
    "dongEN": "Seongsu 2(i)-ga 3(sam)-dong",
    "naverUrl": "https://naver.me/xoH8fSpV",
    "googleUrl": "https://maps.app.goo.gl/qEovCWp8GQdQgLGE6"
  },
  {
    "id": "r_68",
    "district": "jung",
    "nameCN": "Dutum",
    "nameKR": "두툼 korean bbq",
    "lat": 37.55833108979283,
    "lng": 126.96626599995814,
    "category": "烤肉",
    "hashtags": [],
    "googleRating": "4.4",
    "googleReviews": "807份",
    "featuredDish": "",
    "IGreels": "https://www.instagram.com/reel/DZWjwuhvPMY/?utm_source=ig_web_copy_link&igsh=NTc4MTIwNjQ2YQ==",
    "addressEN": "10 Jungnim-ro, Jung District, Seoul",
    "dongKR": "충현동",
    "dongEN": "Chunghyeondong",
    "naverUrl": "https://naver.me/xExWso2C",
    "googleUrl": "https://maps.app.goo.gl/qpJHY7Cbpbg3maMS7"
  },
  {
    "id": "r_69",
    "district": "seongdong",
    "nameCN": "raw coffee stand",
    "nameKR": "로우커피스텐드",
    "lat": 37.54715031276209,
    "lng": 127.04658718454456,
    "category": "點心",
    "hashtags": [],
    "googleRating": "4.5",
    "googleReviews": "193份",
    "featuredDish": "",
    "IGreels": "https://www.instagram.com/p/DZm9EluyseA/",
    "addressEN": "28-2 Wangsimni-ro 4-gil, Seongdong-gu, Seoul",
    "dongKR": "성수1가2동",
    "dongEN": "Seongsu1(il)-ga2(i)-dong",
    "naverUrl": "https://naver.me/Fuz5jrSF",
    "googleUrl": "https://maps.app.goo.gl/M4L4YRPbyMtxRk357"
  },
  {
    "id": "r_70",
    "district": "seongdong",
    "nameCN": "raw coffee stand",
    "nameKR": "로우커피스텐드",
    "lat": 37.54103719292604,
    "lng": 127.059536028781,
    "category": "點心",
    "hashtags": [],
    "googleRating": "4.8",
    "googleReviews": "34份",
    "featuredDish": "",
    "IGreels": "https://www.instagram.com/p/DZm9EluyseA/",
    "addressEN": "272-30 Seongsu-dong 2(i)-ga, Seongdong-gu, Seoul",
    "dongKR": "성수2가3동",
    "dongEN": "Seongsu 2(i)-ga 3(sam)-dong",
    "naverUrl": "https://naver.me/GSDNXnkp",
    "googleUrl": "https://maps.app.goo.gl/Yg74KG7xyBd3PE3w8"
  },
  {
    "id": "r_71",
    "district": "jongno",
    "nameCN": "raw coffee stand",
    "nameKR": "로우커피스텐드",
    "lat": 37.56638640418498,
    "lng": 126.98882647112018,
    "category": "點心",
    "hashtags": [],
    "googleRating": "4.6",
    "googleReviews": "12份",
    "featuredDish": "",
    "IGreels": "https://www.instagram.com/p/DZm9EluyseA/",
    "addressEN": "97-1 Eulji-ro, Jung District, Seoul",
    "dongKR": "종로1·2·3·4가동",
    "dongEN": "Jongno1·2·3·4Gadong",
    "naverUrl": "https://naver.me/5ch3wBat",
    "googleUrl": "https://maps.app.goo.gl/FVqsP2Dfw1TkSx878"
  },
  {
    "id": "r_72",
    "district": "seodaemun",
    "nameCN": "新村奶油燉排骨",
    "nameKR": "소신이쏘",
    "lat": 37.557199599999834,
    "lng": 126.9355218711301,
    "category": "韓式鹹食",
    "hashtags": [],
    "googleRating": "4.2",
    "googleReviews": "483份",
    "featuredDish": "",
    "IGreels": "https://www.instagram.com/p/DYGwzBXsmtH/",
    "addressEN": "19 Yonsei-ro 5ga-gil, Seodaemun-gu, Seoul",
    "dongKR": "신촌동",
    "dongEN": "Sinchon-dong",
    "naverUrl": "https://naver.me/FzSZNB4S",
    "googleUrl": "https://maps.app.goo.gl/DouS6Y4S4tcSHnkJ7"
  },
  {
    "id": "r_73",
    "district": "jongno",
    "nameCN": "無垢屋",
    "nameKR": "무구옥",
    "lat": 37.57638922312301,
    "lng": 126.9798995351945,
    "category": "暖暖ㄉ湯",
    "hashtags": [],
    "googleRating": "4.6",
    "googleReviews": "414份",
    "featuredDish": "",
    "IGreels": "https://www.instagram.com/p/DYGwzBXsmtH/",
    "addressEN": "Seoul, Jongno District, Yulgok-ro 1-gil, 7 한옥",
    "dongKR": "청운효자동",
    "dongEN": "Cheongunhyojadong",
    "naverUrl": "https://naver.me/5vcHnm5u",
    "googleUrl": "https://maps.app.goo.gl/GiBNcRRDxAJgqTXc9"
  },
  {
    "id": "r_74",
    "district": "seongdong",
    "nameCN": "無垢屋",
    "nameKR": "무구옥",
    "lat": 37.544865100000486,
    "lng": 127.0594418355334,
    "category": "暖暖ㄉ湯",
    "hashtags": [],
    "googleRating": "4.7",
    "googleReviews": "361份",
    "featuredDish": "",
    "IGreels": "https://www.instagram.com/p/DYGwzBXsmtH/",
    "addressEN": "Seoul, Seongdong-gu, Achasan-ro 11-gil, 11 무구옥 1층 103호",
    "dongKR": "성수2가3동",
    "dongEN": "Seongsu 2(i)-ga 3(sam)-dong",
    "naverUrl": "https://naver.me/FivZZffz",
    "googleUrl": "https://maps.app.goo.gl/duuD94Ga3C3tFScP9"
  },
  {
    "id": "r_75",
    "district": "yongsan",
    "nameCN": "Hemian Brunch Bar",
    "nameKR": "헤미안",
    "lat": 37.539833634269456,
    "lng": 126.98754139266285,
    "category": "烤肉",
    "hashtags": [],
    "googleRating": "4.4",
    "googleReviews": "807份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "250 Noksapyeong-daero, Yongsan District, Seoul",
    "dongKR": "용산2가동",
    "dongEN": "Yongsan2Gadong",
    "naverUrl": "https://naver.me/GXAWDNzP",
    "googleUrl": "https://maps.app.goo.gl/9LV6nbVF7hHVtU7d6"
  },
  {
    "id": "r_76",
    "district": "jongno",
    "nameCN": "惠化刀削麵",
    "nameKR": "혜화칼국수",
    "lat": 37.5865638698586,
    "lng": 127.00150615862155,
    "category": "麵",
    "hashtags": [],
    "googleRating": "4.0",
    "googleReviews": "481份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "13 Changgyeonggung-ro 35-gil, Jongno District, Seoul",
    "dongKR": "혜화동",
    "dongEN": "Hyehwa-dong",
    "naverUrl": "https://naver.me/xa5RXlox",
    "googleUrl": "https://maps.app.goo.gl/pPSYpuBoiL8pW2Sy6"
  },
  {
    "id": "r_77",
    "district": "jongno",
    "nameCN": "又會再見的辣炒年糕",
    "nameKR": "또보겠지떡볶이집",
    "lat": 37.58185954374501,
    "lng": 126.99981955430528,
    "category": "韓式鹹食",
    "hashtags": [],
    "googleRating": "5.0",
    "googleReviews": "212份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "2 층, 38 Changgyeonggung-ro 26-gil, Jongno District, Seoul",
    "dongKR": "혜화동",
    "dongEN": "Hyehwa-dong",
    "naverUrl": "https://naver.me/5gFc73Q3",
    "googleUrl": "https://maps.app.goo.gl/t8BoGcumBCFrwpFd9"
  },
  {
    "id": "r_78",
    "district": "jongno",
    "nameCN": "柳家辣炒雞",
    "nameKR": "유가네닭갈비",
    "lat": 37.58208273826727,
    "lng": 127.00354307896872,
    "category": "韓式鹹食",
    "hashtags": [],
    "googleRating": "3.9",
    "googleReviews": "94份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "Seoul, Jongno District, 이화동 Daehak-ro 8ga-gil, 89 1층",
    "dongKR": "혜화동",
    "dongEN": "Hyehwa-dong",
    "naverUrl": "https://naver.me/5VmtyyaC",
    "googleUrl": "https://maps.app.goo.gl/6NLjg535gXFRgaEc9"
  },
  {
    "id": "r_79",
    "district": "jongno",
    "nameCN": "蕎麥香那間",
    "nameKR": "메밀향그집",
    "lat": 37.58236770696331,
    "lng": 127.00070686044913,
    "category": "韓式鹹食",
    "hashtags": ["辣燉雞"],
    "googleRating": "4.2",
    "googleReviews": "231份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "72-3 Myeongnyun 4(sa)-ga, Jongno District, Seoul",
    "dongKR": "혜화동",
    "dongEN": "Hyehwa-dong",
    "naverUrl": "https://naver.me/xrSQ1nCV",
    "googleUrl": "https://maps.app.goo.gl/s1LsRc8H9LtxZ428A"
  },
  {
    "id": "r_80",
    "district": "yongsan",
    "nameCN": "Gobongdang",
    "nameKR": "고봉당",
    "lat": 37.53290454734734,
    "lng": 126.97187405744987,
    "category": "韓式鹹食",
    "hashtags": ["辣排骨"],
    "googleRating": "5.0",
    "googleReviews": "3份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "234-5 Hangangno 1(il)-ga, Yongsan District, Seoul",
    "dongKR": "원효로1동",
    "dongEN": "Wonhyoro1-dong",
    "naverUrl": "https://naver.me/GV2tYj49",
    "googleUrl": "https://maps.app.goo.gl/AXcnstBMTUDN7tHQ6"
  },
  {
    "id": "r_81",
    "district": "jongno",
    "nameCN": "100years",
    "nameKR": "100년 설렁탕",
    "lat": 37.5818624643514,
    "lng": 127.00084844744329,
    "category": "暖暖ㄉ湯",
    "hashtags": ["雪濃湯"],
    "googleRating": "4.3",
    "googleReviews": "65份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "Seoul, Jongno District, Daehak-ro 9-gil, 18 1층",
    "dongKR": "혜화동",
    "dongEN": "Hyehwa-dong",
    "naverUrl": "https://naver.me/5apTPGJD",
    "googleUrl": "https://maps.app.goo.gl/gewcDYNjQRLs9yqt7"
  },
  {
    "id": "r_82",
    "district": "jongno",
    "nameCN": "血腸實錄",
    "nameKR": "순대실록",
    "lat": 37.5829721343834,
    "lng": 127.00365314214892,
    "category": "韓式鹹食",
    "hashtags": [],
    "googleRating": "4.5",
    "googleReviews": "2120份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "Seoul, Jongno District, Dongsung-gil, 113 스타벅스 동숭로 아트점 맞은편 1층",
    "dongKR": "혜화동",
    "dongEN": "Hyehwa-dong",
    "naverUrl": "https://naver.me/5tJtlayi",
    "googleUrl": "https://maps.app.goo.gl/z9YPrqLHdDd9Qnsi7"
  },
  {
    "id": "r_83",
    "district": "jongno",
    "nameCN": "PIZZERIA'O",
    "nameKR": "핏제리아오",
    "lat": 37.582030546403104,
    "lng": 127.00428008214597,
    "category": "義大利麵",
    "hashtags": [],
    "googleRating": "4.8",
    "googleReviews": "7188份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "86 Dongsung-gil, Jongno District, Seoul",
    "dongKR": "혜화동",
    "dongEN": "Hyehwa-dong",
    "naverUrl": "https://naver.me/GUwSxgM3",
    "googleUrl": "https://maps.app.goo.gl/jcss31NsKQGKjr6X7"
  },
  {
    "id": "r_84",
    "district": "jongno",
    "nameCN": "煥熙",
    "nameKR": "환희",
    "lat": 37.58283729496752,
    "lng": 127.00026092368552,
    "category": "義大利麵",
    "hashtags": [],
    "googleRating": "4.8",
    "googleReviews": "32份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "Seoul, Jongno District, Daemyeong 1-gil, 16-7 2층",
    "dongKR": "혜화동",
    "dongEN": "Hyehwa-dong",
    "naverUrl": "https://naver.me/xZVbGmAc",
    "googleUrl": "https://maps.app.goo.gl/4Ay6aJpQtwMusdWh8"
  },
  {
    "id": "r_85",
    "district": "jongno",
    "nameCN": "Pasta Market",
    "nameKR": "파스타마켓",
    "lat": 37.58207653360458,
    "lng": 127.00127071138753,
    "category": "義大利麵",
    "hashtags": [],
    "googleRating": "4.8",
    "googleReviews": "732份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "103-6 Myeongnyun 4(sa)-ga, Jongno District, Seoul",
    "dongKR": "혜화동",
    "dongEN": "Hyehwa-dong",
    "naverUrl": "https://naver.me/56R6PRlY",
    "googleUrl": "https://maps.app.goo.gl/p8pcs9DExaKgMTsb9"
  },
  {
    "id": "r_86",
    "district": "jongno",
    "nameCN": "Damsot",
    "nameKR": "담솥",
    "lat": 37.58148479183303,
    "lng": 127.00046135092165,
    "category": "韓式鹹食",
    "hashtags": ["釜飯"],
    "googleRating": "4.2",
    "googleReviews": "15份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "Seoul, Jongno District, Daehak-ro 9-gil, 23-2 1층",
    "dongKR": "혜화동",
    "dongEN": "Hyehwa-dong",
    "naverUrl": "https://naver.me/52R5QY7n",
    "googleUrl": "https://maps.app.goo.gl/eo5ukPxzL3sWYvmq7"
  },
  {
    "id": "r_87",
    "district": "jongno",
    "nameCN": "溫之心",
    "nameKR": "온지심",
    "lat": 37.573130275957,
    "lng": 126.9905081822836,
    "category": "點心",
    "hashtags": [],
    "googleRating": "4.8",
    "googleReviews": "721份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "17 Donhwamun-ro 11da-gil, Jongno District, Seoul",
    "dongKR": "종로1·2·3·4가동",
    "dongEN": "Jongno1·2·3·4Gadong",
    "naverUrl": "https://naver.me/5du4hHup",
    "googleUrl": "https://maps.app.goo.gl/Jb9h2QNS39yVTBpA6"
  },
  {
    "id": "r_88",
    "district": "jongno",
    "nameCN": "Mil Toast",
    "nameKR": "밀토스트",
    "lat": 37.573119200000015,
    "lng": 126.99033687383597,
    "category": "點心",
    "hashtags": [],
    "googleRating": "3.9",
    "googleReviews": "1207份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "30-3 Supyo-ro 28-gil, Jongno District, Seoul",
    "dongKR": "종로1·2·3·4가동",
    "dongEN": "Jongno1·2·3·4Gadong",
    "naverUrl": "https://naver.me/xUw1J6gb",
    "googleUrl": "https://maps.app.goo.gl/hoDzW6E16rJ6vZkF9"
  },
  {
    "id": "r_89",
    "district": "jongno",
    "nameCN": "Cafe Highwaist",
    "nameKR": "카페하이웨스트",
    "lat": 37.57311707414605,
    "lng": 126.99070165422609,
    "category": "點心",
    "hashtags": [],
    "googleRating": "4.2",
    "googleReviews": "305份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "18 Donhwamun-ro 11da-gil, Jongno District, Seoul",
    "dongKR": "종로1·2·3·4가동",
    "dongEN": "Jongno1·2·3·4Gadong",
    "naverUrl": "https://naver.me/IDFU2aDg",
    "googleUrl": "https://maps.app.goo.gl/JYCw67jTaHrHEwLu6"
  },
  {
    "id": "r_90",
    "district": "jongno",
    "nameCN": "益善洞牧場",
    "nameKR": "익선동목장",
    "lat": 37.573164199123305,
    "lng": 126.99112865131859,
    "category": "烤肉",
    "hashtags": [],
    "googleRating": "4.5",
    "googleReviews": "315份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "53 Donhwamun-ro, Jongno District, Seoul",
    "dongKR": "종로1·2·3·4가동",
    "dongEN": "Jongno1·2·3·4Gadong",
    "naverUrl": "https://naver.me/GHvqUTKa",
    "googleUrl": "https://maps.app.goo.gl/pP1hz9MocKoRkuN68"
  },
  {
    "id": "r_91",
    "district": "jongno",
    "nameCN": "松岩溫飯",
    "nameKR": "송암온반",
    "lat": 37.57397639167798,
    "lng": 126.98998664845367,
    "category": "湯飯",
    "hashtags": [],
    "googleRating": "4.9",
    "googleReviews": "479份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "Seoul, Jongno District, Donhwamun-ro 11na-gil, 31-3 1층",
    "dongKR": "종로1·2·3·4가동",
    "dongEN": "Jongno1·2·3·4Gadong",
    "naverUrl": "https://naver.me/513NCLWN",
    "googleUrl": "https://maps.app.goo.gl/589D7ywM7rdAWHeeA"
  },
  {
    "id": "r_93",
    "district": "jongno",
    "nameCN": "小夏鹽田",
    "nameKR": "소하염전",
    "lat": 37.573077948846716,
    "lng": 126.9896958421838,
    "category": "點心",
    "hashtags": [],
    "googleRating": "4.4",
    "googleReviews": "1217份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "21-5 Supyo-ro 28-gil, Jongno District, Seoul",
    "dongKR": "종로1·2·3·4가동",
    "dongEN": "Jongno1·2·3·4Gadong",
    "naverUrl": "https://naver.me/5chuobxW",
    "googleUrl": "https://maps.app.goo.gl/pfX2ocANJPHUwXMg7"
  },
  {
    "id": "r_94",
    "district": "jongno",
    "nameCN": "London Bagel Museum",
    "nameKR": "런던베이글뮤지엄",
    "lat": 37.57918280724872,
    "lng": 126.98615695726794,
    "category": "點心",
    "hashtags": [],
    "googleRating": "4.1",
    "googleReviews": "2289份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "20 Bukchon-ro 4-gil, Jongno District, Seoul",
    "dongKR": "가회동",
    "dongEN": "Gahoe-dong",
    "naverUrl": "https://naver.me/xNLZDTek",
    "googleUrl": "https://maps.app.goo.gl/hwJUYkeVVc19E9bx7"
  },
  {
    "id": "r_95",
    "district": "jongno",
    "nameCN": "百味堂霜淇淋",
    "nameKR": "백미당",
    "lat": 37.58008648012675,
    "lng": 126.98021234547616,
    "category": "點心",
    "hashtags": [],
    "googleRating": "4.4",
    "googleReviews": "522份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "48 Samcheong-ro, Jongno District, Seoul",
    "dongKR": "청운효자동",
    "dongEN": "Cheongunhyojadong",
    "naverUrl": "https://naver.me/GYC9bZbQ",
    "googleUrl": "https://maps.app.goo.gl/wud5p1jQVrYgPQfq9"
  },
  {
    "id": "r_97",
    "district": "jongno",
    "nameCN": "紅豆粥",
    "nameKR": "서울서둘째로잘하는집",
    "lat": 37.586206562745886,
    "lng": 126.98182224933925,
    "category": "點心",
    "hashtags": [],
    "googleRating": "4.4",
    "googleReviews": "917份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "122-1 Samcheong-ro, Jongno District, Seoul",
    "dongKR": "삼청동",
    "dongEN": "Samcheong-dong",
    "naverUrl": "https://naver.me/xAFCYsSK",
    "googleUrl": "https://maps.app.goo.gl/QmhYV2nnEf3dWwj99"
  },
  {
    "id": "r_98",
    "district": "jongno",
    "nameCN": "摩西年糕鍋",
    "nameKR": "먹쉬돈나",
    "lat": 37.58343774397169,
    "lng": 126.98198166036768,
    "category": "韓式鹹食",
    "hashtags": [],
    "googleRating": "3.9",
    "googleReviews": "1205份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "90-1 Samcheong-ro, Jongno District, Seoul",
    "dongKR": "삼청동",
    "dongEN": "Samcheong-dong",
    "naverUrl": "https://naver.me/G0DXVSIf",
    "googleUrl": "https://maps.app.goo.gl/X1Qeg6C2DjCz5Bth8"
  },
  {
    "id": "r_99",
    "district": "jongno",
    "nameCN": "Jungdamun",
    "nameKR": "정담은보쌈",
    "lat": 37.57885275091807,
    "lng": 126.98611008982704,
    "category": "韓式鹹食",
    "hashtags": ["菜包肉", "拌麵"],
    "googleRating": "4.5",
    "googleReviews": "294份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "33-9 Gyedong-gil, Jongno District, Seoul",
    "dongKR": "가회동",
    "dongEN": "Gahoe-dong",
    "naverUrl": "https://naver.me/FZ275N8q",
    "googleUrl": "https://maps.app.goo.gl/6SMTVEe5avv9i32u6"
  },
  {
    "id": "r_100",
    "district": "seongdong",
    "nameCN": "古友",
    "nameKR": "고우성수",
    "lat": 37.54389442716168,
    "lng": 127.05071213130672,
    "category": "韓式鹹食",
    "hashtags": ["釜飯"],
    "googleRating": "4.3",
    "googleReviews": "117份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "Seoul, Seongdong-gu, Yeonmujang-gil, 9-1 2층",
    "dongKR": "성수1가2동",
    "dongEN": "Seongsu1(il)-ga2(i)-dong",
    "naverUrl": "https://naver.me/GYC9jWCq",
    "googleUrl": "https://maps.app.goo.gl/5gJofVpTgWTL6QXL9"
  },
  {
    "id": "r_101",
    "district": "seongdong",
    "nameCN": "Rafre Fruit",
    "nameKR": "라프레플루트",
    "lat": 37.54725392387013,
    "lng": 127.03944875131383,
    "category": "漂亮咖",
    "hashtags": [],
    "googleRating": "4.2",
    "googleReviews": "418份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "Seoul, Seongdong-gu, Seoulsup 2-gil, 8-8 2층",
    "dongKR": "응봉동",
    "dongEN": "Eungbong-dong",
    "naverUrl": "https://naver.me/GbDFc7un",
    "googleUrl": "https://maps.app.goo.gl/AhwptwcyLpXNJd8J8"
  },
  {
    "id": "r_102",
    "district": "jongno",
    "nameCN": "朴家綠豆煎餅",
    "nameKR": "박가네 빈대떡",
    "lat": 37.57053824396187,
    "lng": 127.00084701818916,
    "category": "韓式鹹食",
    "hashtags": ["廣藏市場"],
    "googleRating": "3.8",
    "googleReviews": "1107份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "7 Jong-ro 32-gil, Jongno District, Seoul",
    "dongKR": "종로5·6가동",
    "dongEN": "Jongno5·6Gadong",
    "naverUrl": "https://naver.me/FDnCdFbP",
    "googleUrl": "https://maps.app.goo.gl/9LsvC7uDEuNNuYfs5"
  },
  {
    "id": "r_103",
    "district": "jongno",
    "nameCN": "順姬家綠豆煎餅",
    "nameKR": "원조순희네빈대떡",
    "lat": 37.57057889366251,
    "lng": 127.00070523994286,
    "category": "韓式鹹食",
    "hashtags": ["廣藏市場"],
    "googleRating": "4.0",
    "googleReviews": "1716份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "5 Jong-ro 32-gil, Jongno District, Seoul",
    "dongKR": "종로5·6가동",
    "dongEN": "Jongno5·6Gadong",
    "naverUrl": "https://naver.me/5du4ywfn",
    "googleUrl": "https://maps.app.goo.gl/sWCJ7fZAcww7t8Hb6"
  },
  {
    "id": "r_104",
    "district": "jongno",
    "nameCN": "母女飯卷",
    "nameKR": "모녀김밥",
    "lat": 37.57064268707154,
    "lng": 127.00054229280822,
    "category": "韓式鹹食",
    "hashtags": ["廣藏市場"],
    "googleRating": "4.2",
    "googleReviews": "12份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "Jong-ro, 종로5가 Jongno District, Seoul",
    "dongKR": "종로5·6가동",
    "dongEN": "Jongno5·6Gadong",
    "naverUrl": "https://naver.me/5du4n5R5",
    "googleUrl": "https://maps.app.goo.gl/BY4921KE5dBoWmQ66"
  },
  {
    "id": "r_105",
    "district": "jongno",
    "nameCN": "姜氏炒年糕",
    "nameKR": "강가네 떡볶이",
    "lat": 37.57059745807241,
    "lng": 127.00042083888317,
    "category": "韓式鹹食",
    "hashtags": ["廣藏市場"],
    "googleRating": "4.2",
    "googleReviews": "106份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "Seoul, Jongno District, Jong-ro 32-gil, 2 아케이트 101호",
    "dongKR": "종로1·2·3·4가동",
    "dongEN": "Jongno1·2·3·4Gadong",
    "naverUrl": "https://naver.me/FW6hs0TE",
    "googleUrl": "https://maps.app.goo.gl/TkYnfZD1fYr4aC7Q6"
  },
  {
    "id": "r_106",
    "district": "jongno",
    "nameCN": "Eunseong Sashimi",
    "nameKR": "은성횟집",
    "lat": 37.5702791050721,
    "lng": 126.99871329041264,
    "category": "韓式鹹食",
    "hashtags": ["辣鱈魚湯", "廣藏市場"],
    "googleRating": "3.9",
    "googleReviews": "794份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "45 Changgyeonggung-ro, Jongno District, Seoul",
    "dongKR": "종로1·2·3·4가동",
    "dongEN": "Jongno1·2·3·4Gadong",
    "naverUrl": "https://naver.me/5du4OBYs",
    "googleUrl": "https://maps.app.goo.gl/QUQwZg1nxXp3FVxg8"
  },
  {
    "id": "r_107",
    "district": "jongno",
    "nameCN": "Buchon Yukhoe",
    "nameKR": "부촌육회",
    "lat": 37.570333378616716,
    "lng": 126.99989957939047,
    "category": "韓式鹹食",
    "hashtags": ["拌生牛肉", "廣藏市場"],
    "googleRating": "4.4",
    "googleReviews": "2184份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "200-12 종로, Jongno District, Seoul",
    "dongKR": "종로1·2·3·4가동",
    "dongEN": "Jongno1·2·3·4Gadong",
    "naverUrl": "https://naver.me/5eUcm0Tr",
    "googleUrl": "https://maps.app.goo.gl/CyPQjPCLrZjK7q9r8"
  },
  {
    "id": "r_108",
    "district": "seongdong",
    "nameCN": "陵洞水芹菜",
    "nameKR": "능동미나리",
    "lat": 37.542749408668946,
    "lng": 127.05395657902959,
    "category": "韓式鹹食",
    "hashtags": [],
    "googleRating": "4.5",
    "googleReviews": "501份",
    "featuredDish": "水芹菜生牛肉拌飯、水芹菜牛五花牛骨湯",
    "IGreels": "",
    "addressEN": "42 Yeonmujang-gil, Seongdong-gu, Seoul",
    "dongKR": "성수2가3동",
    "dongEN": "Seongsu 2(i)-ga 3(sam)-dong",
    "naverUrl": "https://naver.me/5iTdPV9Z",
    "googleUrl": "https://maps.app.goo.gl/qpFbvxw7EfaeUFHcA"
  },
  {
    "id": "r_109",
    "district": "mapo",
    "nameCN": "林間路肉舖",
    "nameKR": "숲길정육점",
    "lat": 37.562548101789865,
    "lng": 126.9247921188384,
    "category": "烤肉",
    "hashtags": [],
    "googleRating": "4.7",
    "googleReviews": "121份",
    "featuredDish": "豬頸肉",
    "IGreels": "",
    "addressEN": "256 Donggyo-ro, Mapo-gu, Seoul",
    "dongKR": "연남동",
    "dongEN": "Yeonnam-dong",
    "naverUrl": "https://naver.me/xAFCY07P",
    "googleUrl": "https://maps.app.goo.gl/Zx2o7MD39CUTf6gM8"
  },
  {
    "id": "r_110",
    "district": "jongno",
    "nameCN": "鐘路雞林蒜蓉辣雞湯",
    "nameKR": "종로계림닭도리탕원조",
    "lat": 37.57014626189503,
    "lng": 126.99449988553822,
    "category": "暖暖ㄉ湯",
    "hashtags": [],
    "googleRating": "4.1",
    "googleReviews": "1731份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "39 Donhwamun-ro 4-gil, Jongno District, Seoul",
    "dongKR": "종로1·2·3·4가동",
    "dongEN": "Jongno1·2·3·4Gadong",
    "naverUrl": "https://naver.me/x2jQdMii",
    "googleUrl": "https://maps.app.goo.gl/UTbtQzt8ZAuQi66v6"
  },
  {
    "id": "r_111",
    "district": "jung",
    "nameCN": "鐘路雞林蒜蓉辣雞湯",
    "nameKR": "종로계림닭도리탕원조",
    "lat": 37.56235782446681,
    "lng": 126.99551094831301,
    "category": "暖暖ㄉ湯",
    "hashtags": [],
    "googleRating": "4.6",
    "googleReviews": "43份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "28-5 Gwanghui-dong, Jung District, Seoul",
    "dongKR": "을지로동",
    "dongEN": "Euljirodong",
    "naverUrl": "https://naver.me/F0z21NZY",
    "googleUrl": "https://maps.app.goo.gl/mppJ4E72V8pwwHNdA"
  },
  {
    "id": "r_112",
    "district": "mapo",
    "nameCN": "鐘路雞林蒜蓉辣雞湯",
    "nameKR": "종로계림닭도리탕원조",
    "lat": 37.56146761397018,
    "lng": 126.92575416478685,
    "category": "暖暖ㄉ湯",
    "hashtags": [],
    "googleRating": "4.5",
    "googleReviews": "30份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "Seoul, Mapo-gu, Donggyo-ro 38-gil, 33 102호",
    "dongKR": "연남동",
    "dongEN": "Yeonnam-dong",
    "naverUrl": "https://naver.me/xFLunMlm",
    "googleUrl": "https://maps.app.goo.gl/GUyyJ5kXxCz4vX2X6"
  }
];

const ATTRACTIONS = [
  {
    "id": "a_1",
    "district": "mapo",
    "nameCN": "Eternalog",
    "nameKR": "이터널로그 홍대",
    "lat": 37.556241321378,
    "lng": 126.92792537116433,
    "categories": ["拍貼機"],
    "hashtags": [],
    "introText": "歐洲進口墨水沖印機台✨",
    "addressEN": "Seoul, Mapo-gu, Wausan-ro 29-gil, 48-24 1층 103호",
    "googleUrl": "https://maps.app.goo.gl/QAsJaQQDY6DNoSoy8",
    "naverUrl": "https://naver.me/G4WoQkm6",
    "IGreels": "https://www.instagram.com/reels/DZR-ObkimiU/",
    "dongKR": "서교동",
    "dongEN": "Seogyo-dong"
  },
  {
    "id": "a_2",
    "district": "mapo",
    "nameCN": "Little Riddle Store",
    "nameKR": "리틀리들",
    "lat": 37.556822115833164,
    "lng": 126.92871384232868,
    "categories": ["選物店"],
    "hashtags": [],
    "introText": "美式復古風，很多可愛小物、有古著",
    "addressEN": "서울 Mapo-gu, Wausan-ro 37-gil, 42 1층",
    "googleUrl": "https://maps.app.goo.gl/JHYbauKFvvhX4pu99",
    "naverUrl": "https://naver.me/57VZUZHx",
    "IGreels": "https://www.instagram.com/reels/DZR-ObkimiU/",
    "dongKR": "서교동",
    "dongEN": "Seogyo-dong"
  },
  {
    "id": "a_3",
    "district": "mapo",
    "nameCN": "SUBACO",
    "nameKR": "수바코 홍대점",
    "lat": 37.556843015826026,
    "lng": 126.92859612883565,
    "categories": ["選物店", "拍貼機"],
    "hashtags": [],
    "introText": "日式復古風，有散裝扭蛋、吊飾、姓名貼、日式拍貼",
    "addressEN": "46 Wausan-ro 37-gil, Donggyo-dong, Mapo-gu, Seoul",
    "googleUrl": "https://maps.app.goo.gl/f7AW38AHJQncFyou9",
    "naverUrl": "https://naver.me/5fIpan7p",
    "IGreels": "https://www.instagram.com/reels/DZR-ObkimiU/",
    "dongKR": "서교동",
    "dongEN": "Seogyo-dong"
  },
  {
    "id": "a_4",
    "district": "jongno",
    "nameCN": "OxO Camera",
    "nameKR": "OxO 카메라",
    "lat": 37.569535975557386,
    "lng": 126.99518092288444,
    "categories": ["隱藏小店"],
    "hashtags": [],
    "introText": "老商家裡的CCD專賣店",
    "addressEN": "서울 종로구 청계천로 159 세운상가 2층 나203호",
    "googleUrl": "https://maps.app.goo.gl/tPrGNAhy9vMFoJ5L7",
    "naverUrl": "https://naver.me/x1uIRtz2",
    "IGreels": "https://www.instagram.com/p/DUxusvdkoNt/",
    "dongKR": "종로1·2·3·4가동",
    "dongEN": "Jongno1·2·3·4Gadong"
  },
  {
    "id": "a_5",
    "district": "seongdong",
    "nameCN": "29cm.home",
    "nameKR": "이구홈 성수",
    "lat": 37.54256431220418,
    "lng": 127.05575764030418,
    "categories": ["選物店"],
    "hashtags": [],
    "introText": "家居選品",
    "addressEN": "315-10 Seongsu-dong 2(i)-ga, Seongdong-gu, Seoul",
    "googleUrl": "https://maps.app.goo.gl/5vYeQbsKkgxYDJhA6",
    "naverUrl": "https://naver.me/xv6vxWUD",
    "dongKR": "성수2가3동",
    "dongEN": "Seongsu 2(i)-ga 3(sam)-dong"
  },
  {
    "id": "a_6",
    "district": "seongdong",
    "nameCN": "Musinsa Megastore Seongsu",
    "nameKR": "무신사 메가스토어",
    "lat": 37.54029719283844,
    "lng": 127.05588367782292,
    "categories": ["服飾店"],
    "hashtags": [],
    "addressEN": "62 Seongsui-ro, Seongdong-gu, Seoul",
    "googleUrl": "https://maps.app.goo.gl/QWK9w6mjRxYf6i5dA",
    "naverUrl": "https://naver.me/5LQ3XxMP",
    "dongKR": "성수2가3동",
    "dongEN": "Seongsu 2(i)-ga 3(sam)-dong"
  },
  {
    "id": "a_7",
    "district": "jung",
    "nameCN": "NOWNEW",
    "nameKR": "나우뉴",
    "lat": 37.56170324292242,
    "lng": 126.98413599991206,
    "categories": ["服飾店"],
    "hashtags": [],
    "addressEN": "22-4 Chungmuro 1(il)-ga, Jung District, Seoul",
    "googleUrl": "https://maps.app.goo.gl/7YH7HemMHMKCZEs38",
    "naverUrl": "https://naver.me/xq3dyoIO",
    "dongKR": "소공동",
    "dongEN": "Sogong-dong"
  },
  {
    "id": "a_8",
    "district": "seongdong",
    "nameCN": "KioskKiosk",
    "nameKR": "키오스크키오스크",
    "lat": 37.54464560000002,
    "lng": 127.04528520665855,
    "categories": ["文具店"],
    "hashtags": [],
    "addressEN": "Seoul, Seongdong-gu, Wangsimni-ro, 80-1 2층",
    "googleUrl": "https://maps.app.goo.gl/PvWYxM4T1jD5ukrJ8",
    "naverUrl": "https://naver.me/xP8mXrhV",
    "dongKR": "성수1가2동",
    "dongEN": "Seongsu1(il)-ga2(i)-dong"
  },
  {
    "id": "a_9",
    "district": "seodaemun",
    "nameCN": "Object",
    "nameKR": "오브젝트",
    "lat": 37.5557091578171,
    "lng": 126.92978379280154,
    "categories": ["文具店"],
    "hashtags": [],
    "addressEN": "13 Wausan-ro 35-gil, Mapo-gu, Seoul",
    "googleUrl": "https://maps.app.goo.gl/n2eicUB84f4jemwP8",
    "naverUrl": "https://naver.me/GBFH9TWg",
    "dongKR": "신촌동",
    "dongEN": "Sinchon-dong"
  },
  {
    "id": "a_10",
    "district": "jongno",
    "nameCN": "Object",
    "nameKR": "오브젝트 삼청점",
    "lat": 37.5794071540477,
    "lng": 126.98460094224072,
    "categories": ["文具店"],
    "hashtags": [],
    "addressEN": "11 Jae-dong, Jongno District, Seoul",
    "googleUrl": "https://maps.app.goo.gl/sq9DVVM5ysRNjoQ38",
    "naverUrl": "https://naver.me/502M0pvf",
    "dongKR": "삼청동",
    "dongEN": "Samcheong-dong"
  },
  {
    "id": "a_11",
    "district": "seongdong",
    "nameCN": "Object Seongsu",
    "nameKR": "포셋 성수",
    "lat": 37.54782757174095,
    "lng": 127.04130617003732,
    "categories": ["文具店"],
    "hashtags": [],
    "addressEN": "Seoul, Seongdong-gu, Seoulsup-gil, 36 2층",
    "googleUrl": "https://maps.app.goo.gl/kUAKrMxqp6U1pevW7",
    "naverUrl": "https://naver.me/GYC9o9US",
    "IGreels": "https://www.instagram.com/p/C3b7PCardft/?img_index=8",
    "dongKR": "성수1가2동",
    "dongEN": "Seongsu1(il)-ga2(i)-dong"
  },
  {
    "id": "a_12",
    "district": "seongdong",
    "nameCN": "Hidden Blind Box Minimart",
    "nameKR": "히든 블라인드 박스 미니마트",
    "lat": 37.542992594889604,
    "lng": 127.05616284268324,
    "categories": ["盲盒店"],
    "hashtags": [],
    "introText": "滿滿的吊飾扭蛋盲盒",
    "addressEN": "Seoul, Seongdong-gu, 지하 1층 ８−１ 연무장9길",
    "googleUrl": "https://maps.app.goo.gl/ThhwAnpTmUmiUzwL7",
    "naverUrl": "https://naver.me/50BHtEtf",
    "IGreels": "https://www.instagram.com/reel/DVi9Cs2D6G2/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==",
    "dongKR": "성수2가3동",
    "dongEN": "Seongsu 2(i)-ga 3(sam)-dong"
  },
  {
    "id": "a_13",
    "district": "seongdong",
    "nameCN": "MUSINSA EMPTY SEONGSU",
    "nameKR": "무신사 엠프티 성수",
    "lat": 37.54363455246723,
    "lng": 127.05661730234029,
    "categories": ["服飾店"],
    "hashtags": [],
    "addressEN": "97 Seongsui-ro, Seongdong-gu, Seoul",
    "googleUrl": "https://maps.app.goo.gl/ABiyGuXGL14L1DmW9",
    "naverUrl": "https://naver.me/F3TX0JrD",
    "dongKR": "성수2가3동",
    "dongEN": "Seongsu 2(i)-ga 3(sam)-dong"
  },
  {
    "id": "a_14",
    "district": "jongno",
    "nameCN": "Allwrite",
    "nameKR": "올라이트 서촌점",
    "lat": 37.578917893833875,
    "lng": 126.96974084797283,
    "categories": ["文具店"],
    "hashtags": [],
    "addressEN": "102번지 Chebu-dong, Jongno District, Seoul",
    "googleUrl": "https://maps.app.goo.gl/Ny3x6eu87ui2tacH8",
    "naverUrl": "https://naver.me/FLyT8zDI",
    "dongKR": "청운효자동",
    "dongEN": "Cheongunhyojadong"
  },
  {
    "id": "a_15",
    "district": "jongno",
    "nameCN": "InOurMansion",
    "nameKR": "인아워맨션",
    "lat": 37.580106000000015,
    "lng": 126.98664963549422,
    "categories": ["文具店"],
    "hashtags": [],
    "addressEN": "Seoul, Jongno District, Gyedong-gil, 63 1층",
    "googleUrl": "https://maps.app.goo.gl/cfLdzCJeEUaWyLBa8",
    "naverUrl": "https://naver.me/xRhEIXGJ",
    "dongKR": "가회동",
    "dongEN": "Gahoe-dong"
  },
  {
    "id": "a_16",
    "district": "seongdong",
    "nameCN": "Point of View",
    "nameKR": "POINT of VIEW SEOUL",
    "lat": 37.54341880000002,
    "lng": 127.05137936432989,
    "categories": ["文具店"],
    "hashtags": [],
    "addressEN": "18 Yeonmujang-gil, Seongdong-gu, Seoul",
    "googleUrl": "https://maps.app.goo.gl/QnUkjHsPHqNbwVcs7",
    "naverUrl": "https://naver.me/GL8if0xg",
    "dongKR": "성수1가2동",
    "dongEN": "Seongsu1(il)-ga2(i)-dong"
  },
  {
    "id": "a_17",
    "district": "mapo",
    "nameCN": "Made by",
    "nameKR": "메이드바이 홍대",
    "lat": 37.559746057414884,
    "lng": 126.92636777107641,
    "categories": ["文具店"],
    "hashtags": [],
    "addressEN": "147-75 Donggyo-dong, Mapo-gu, Seoul",
    "googleUrl": "https://maps.app.goo.gl/1VmG2XVw6zYDM7JRA",
    "naverUrl": "https://naver.me/FafyvWX6",
    "dongKR": "연남동",
    "dongEN": "Yeonnam-dong"
  },
  {
    "id": "a_18",
    "district": "mapo",
    "nameCN": "LOOF",
    "nameKR": "루프 홍대점",
    "lat": 37.553805258672185,
    "lng": 126.92191418922492,
    "categories": ["服飾店"],
    "hashtags": [],
    "addressEN": "Seoul, Mapo-gu, Hongik-ro 3-gil, 20 지하 1층",
    "googleUrl": "https://maps.app.goo.gl/P2J7Guq5hpcxhxe6A",
    "naverUrl": "https://naver.me/x4F6tqMM",
    "dongKR": "서교동",
    "dongEN": "Seogyo-dong"
  },
  {
    "id": "a_19",
    "district": "mapo",
    "nameCN": "M. Playground",
    "nameKR": "엠플레이그라운드 홍대2호점",
    "lat": 37.5532943050855,
    "lng": 126.9220469796704,
    "categories": ["服飾店"],
    "hashtags": [],
    "addressEN": "94 Eoulmadang-ro, Mapo-gu, Seoul",
    "googleUrl": "https://maps.app.goo.gl/kTaUK1xZKN3MQSuZ6",
    "naverUrl": "https://naver.me/GkR3c9Xw",
    "dongKR": "서교동",
    "dongEN": "Seogyo-dong"
  },
  {
    "id": "a_20",
    "district": "mapo",
    "nameCN": "ORMUSEA",
    "nameKR": "오알 뮤제아",
    "lat": 37.55363571128185,
    "lng": 126.92225016432988,
    "categories": ["服飾店"],
    "hashtags": [],
    "addressEN": "98 Eoulmadang-ro, Mapo-gu, Seoul",
    "googleUrl": "https://maps.app.goo.gl/dCzkUh3VkY25BG1A8",
    "naverUrl": "https://naver.me/Gubc4ZRl",
    "dongKR": "서교동",
    "dongEN": "Seogyo-dong"
  },
  {
    "id": "a_21",
    "district": "mapo",
    "nameCN": "I am Joy",
    "nameKR": "뉴뉴 서교점",
    "lat": 37.55473611103067,
    "lng": 126.92641419991206,
    "categories": ["服飾店"],
    "hashtags": [],
    "addressEN": "40 Wausan-ro 27-gil, Seogyo-dong, Mapo-gu, Seoul",
    "googleUrl": "https://maps.app.goo.gl/Rw6yHNCXohgeYKfc6",
    "naverUrl": "https://naver.me/5hulX6fi",
    "dongKR": "서교동",
    "dongEN": "Seogyo-dong"
  },
  {
    "id": "a_22",
    "district": "mapo",
    "nameCN": "LOOFON",
    "nameKR": "루프온홍대점",
    "lat": 37.55227105869464,
    "lng": 126.92210470665854,
    "categories": ["服飾店"],
    "hashtags": [],
    "addressEN": "Seoul, Mapo-gu, Wausan-ro 21-gil, 31 지하 1층",
    "googleUrl": "https://maps.app.goo.gl/7q7MynJpo3D987JK8",
    "naverUrl": "https://naver.me/FetU1sKR",
    "dongKR": "서교동",
    "dongEN": "Seogyo-dong"
  },
  {
    "id": "a_23",
    "district": "mapo",
    "nameCN": "Zero Space",
    "nameKR": "제로스페이스 망원",
    "lat": 37.55455105830431,
    "lng": 126.90377545758335,
    "categories": ["選物店"],
    "hashtags": [],
    "addressEN": "398-2 Mangwon-dong, Mapo-gu, Seoul",
    "googleUrl": "https://maps.app.goo.gl/iMCrHw7JZMaifTTo7",
    "naverUrl": "https://naver.me/5pws79mV",
    "dongKR": "망원2동",
    "dongEN": "Mangwon 2(i)-dong"
  },
  {
    "id": "a_24",
    "district": "mapo",
    "nameCN": "Warmgreytail",
    "nameKR": "웜그레이테일",
    "lat": 37.55535979455732,
    "lng": 126.90515124229265,
    "categories": ["選物店"],
    "hashtags": [],
    "introText": "可愛手帕襪子明信片",
    "addressEN": "94 Poeun-ro, 망원제1동 Mapo-gu, Seoul",
    "googleUrl": "https://maps.app.goo.gl/Zj8mMKur124FzGQcA",
    "naverUrl": "https://naver.me/5l7kwEJw",
    "IGreels": "https://www.instagram.com/p/DZm6UU2i9YO/",
    "dongKR": "망원2동",
    "dongEN": "Mangwon 2(i)-dong"
  },
  {
    "id": "a_25",
    "district": "mapo",
    "nameCN": "Zero Space",
    "nameKR": "제로퍼제로",
    "lat": 37.55453830000685,
    "lng": 126.9037539999601,
    "categories": ["文具店"],
    "hashtags": [],
    "introText": "有紙膠帶ㄛ",
    "addressEN": "398-2 Mangwon-dong, Mapo-gu, Seoul",
    "googleUrl": "https://maps.app.goo.gl/oZGYd8E7nida8nLK7",
    "naverUrl": "https://naver.me/5pws79mV",
    "IGreels": "https://www.instagram.com/p/DZm6UU2i9YO/",
    "dongKR": "망원2동",
    "dongEN": "Mangwon 2(i)-dong"
  },
  {
    "id": "a_26",
    "district": "mapo",
    "nameCN": "Lazy Cactus",
    "nameKR": "웅크린선인장",
    "lat": 37.55501659452047,
    "lng": 126.9050155999747,
    "categories": ["選物店"],
    "hashtags": [],
    "introText": "仙人掌IP",
    "addressEN": "404-39 Mangwon-dong, Mapo-gu, Seoul",
    "googleUrl": "https://maps.app.goo.gl/94rBzz1yZR1y7m696",
    "naverUrl": "https://naver.me/xxY2UZfm",
    "IGreels": "https://www.instagram.com/p/DZm6UU2i9YO/",
    "dongKR": "망원2동",
    "dongEN": "Mangwon 2(i)-dong"
  },
  {
    "id": "a_27",
    "district": "mapo",
    "nameCN": "Discover Good Goods",
    "nameKR": "디스커버 굿 굿즈",
    "lat": 37.55447460000002,
    "lng": 126.90554992880797,
    "categories": ["選物店"],
    "hashtags": [],
    "introText": "走質感路線",
    "addressEN": "Seoul, Mapo-gu, Poeun-ro, 84 2 층",
    "googleUrl": "https://maps.app.goo.gl/wvqzXsP2kfFYr79W7",
    "naverUrl": "https://naver.me/xucpnWgo",
    "IGreels": "https://www.instagram.com/p/DZm6UU2i9YO/",
    "dongKR": "망원2동",
    "dongEN": "Mangwon 2(i)-dong"
  }
];

const THEATERS = [
  {
    "id": "t_1",
    "district": "songpa",
    "nameCN": "Charlotte Theater",
    "nameKR": "샤롯데씨어터",
    "lat": 37.510741714193415,
    "lng": 127.09974210768064,
    "categories": ["已購票"],
    "hashtags": [],
    "descText": "Frozen 겨울왕국",
    "theaterUrl": "https://www.kontenx.net/shows/2600093",
    "addressEN": "Seoul, Songpa District, 올림픽로 240",
    "googleUrl": "https://maps.app.goo.gl/jm9jMAEXHf1Woa3P8",
    "naverUrl": "https://naver.me/xique5B3",
    "dongKR": "잠실3동",
    "dongEN": "Jamsil 3(sam)-dong"
  },
  {
    "id": "t_2",
    "district": "jongno",
    "nameCN": "Curtain call",
    "nameKR": "뮤지컬펍 커튼콜",
    "lat": 37.58249397203444,
    "lng": 127.00307696720526,
    "categories": ["已購票"],
    "hashtags": [],
    "descText": "一定要去的啊(ง⸝⸝ᵒ̴̶̷ωᵒ̴̶̷⸝⸝)ว🎶",
    "theaterUrl": "https://www.instagram.com/curtaincall_star/",
    "addressEN": "22 Daehak-ro 12-gil, Jongno District, Seoul",
    "googleUrl": "https://maps.app.goo.gl/jyMWAZjviqVE41dW7",
    "naverUrl": "https://naver.me/FQVGKSI0",
    "dongKR": "혜화동",
    "dongEN": "Hyehwa-dong"
  },
  {
    "id": "t_3",
    "district": "jung",
    "nameCN": "忠武藝術中心 大劇場",
    "nameKR": "충무아트센터",
    "lat": 37.565937576274976,
    "lng": 127.0148377383688,
    "categories": ["美國版權"],
    "hashtags": [],
    "descText": "Dear Evan Hansen 디어에반 핸슨",
    "theaterUrl": "https://www.kontenx.net/shows/2600096",
    "addressEN": "387 Toegye-ro, Jung District, Seoul",
    "googleUrl": "https://maps.app.goo.gl/QijnyWEzcACC1veRA",
    "naverUrl": "https://naver.me/x8tpHeCf",
    "dongKR": "신당동",
    "dongEN": "Sindang-dong"
  },
  {
    "id": "t_4",
    "district": "gangseo",
    "nameCN": "LG藝術中心 LG SIGNATURE廳",
    "nameKR": "LG아트센터 서울",
    "lat": 37.56512068936257,
    "lng": 126.82958266720433,
    "categories": ["已購票"],
    "hashtags": [],
    "descText": "DRACULA 드라큘라",
    "theaterUrl": "https://www.instagram.com/reel/DYgaoTASP2Q/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==",
    "addressEN": "136 Magokjungang-ro, Gangseo-gu, Seoul",
    "googleUrl": "https://maps.app.goo.gl/BqQ6yZifvASVuBnw5",
    "naverUrl": "https://naver.me/GRo4xAgP",
    "dongKR": "가양1동",
    "dongEN": "Gayang 1(il)-dong"
  },
  {
    "id": "t_5",
    "district": "jongno",
    "nameCN": "YES24 Art One",
    "nameKR": "예스24아트원",
    "lat": 37.58022306943089,
    "lng": 127.00395748069816,
    "categories": ["韓國原創", "英國版權"],
    "hashtags": [],
    "shows": [
      {
        "descText": "1館 - 斷背山 브로크백 마운틴",
        "theaterUrl": "https://www.kontenx.net/shows/2600092"
      },
      {
        "descText": "2館 - Stravinsky 스트라빈스키",
        "theaterUrl": "https://www.kontenx.net/shows/2600090"
      },
      {
        "descText": "3館 - Iolaus 이올라오스",
        "theaterUrl": "https://yes24stage.com/ko/show/detail.php?id=779&P=1&search_obj=&search_str=&type=2&perform_date=20260621"
      }
    ],
    "addressEN": "83 Daehak-ro 12-gil, Jongno District, Seoul",
    "googleUrl": "https://maps.app.goo.gl/e4NRPnBj2dpgwgb9A",
    "naverUrl": "https://naver.me/GUw96B72",
    "dongKR": "혜화동",
    "dongEN": "Hyehwa-dong"
  },
  {
    "id": "t_6",
    "district": "jongno",
    "nameCN": "同德女子大學公演藝術中心 Cotton Hall",
    "nameKR": "동덕여자대학교 공연예술센터",
    "lat": 37.58370837424109,
    "lng": 127.003267709534,
    "categories": ["韓國原創"],
    "hashtags": [],
    "descText": "物種起源 종의 기원",
    "theaterUrl": "https://www.kontenx.net/shows/2600087",
    "addressEN": "126 Dongsung-gil, Dongsung-dong, Jongno District, Seoul",
    "googleUrl": "https://maps.app.goo.gl/ogDvsC2MVrWm8n6SA",
    "naverUrl": "https://naver.me/xJiBwuVC",
    "dongKR": "혜화동",
    "dongEN": "Hyehwa-dong"
  },
  {
    "id": "t_7",
    "district": "jongno",
    "nameCN": "弘益大學大學路藝術中心",
    "nameKR": "홍익대학교 대학로 아트센터",
    "lat": 37.57665566902455,
    "lng": 127.00185119604066,
    "categories": ["韓國原創"],
    "hashtags": [],
    "descText": "帕格尼尼 파가니니",
    "theaterUrl": "https://www.kontenx.net/shows/2600077",
    "addressEN": "57 Daehak-ro, Jongno District, Seoul",
    "googleUrl": "https://maps.app.goo.gl/oLJJ2iPFGrbeXG3A7",
    "naverUrl": "https://naver.me/FEUpPTpe",
    "dongKR": "이화동",
    "dongEN": "Ihwa-dong"
  },
  {
    "id": "t_8",
    "district": "jongno",
    "nameCN": "Link Art Center",
    "nameKR": "링크아트센터",
    "lat": 37.584628176238795,
    "lng": 127.00234672487679,
    "categories": ["韓國原創"],
    "hashtags": [],
    "shows": [
      {
        "descText": "BUGS Hall - BLACK MARY POPPINS 블랙메리포핀스",
        "theaterUrl": "https://www.kontenx.net/shows/2600076"
      },
      {
        "descText": "PAYCO Hall - 死之詠贊 사의찬미",
        "theaterUrl": "https://www.kontenx.net/shows/2600091"
      }
    ],
    "addressEN": "29 Daehak-ro 14-gil, Jongno District, Seoul",
    "googleUrl": "https://maps.app.goo.gl/HWQwNxshAXLap2Zg6",
    "naverUrl": "https://naver.me/x2jQCvuM",
    "dongKR": "혜화동",
    "dongEN": "Hyehwa-dong"
  },
  {
    "id": "t_9",
    "district": "jongno",
    "nameCN": "Link Art Center Dream",
    "nameKR": "링크아트센터드림",
    "lat": 37.58331067654012,
    "lng": 127.00329169604102,
    "categories": ["韓國原創"],
    "hashtags": [],
    "shows": [
      {
        "descText": "1館 - WIDERSTAND 비더슈탄트",
        "theaterUrl": "https://www.kontenx.net/shows/2600223"
      },
      {
        "descText": "2館 - 47 사칠",
        "theaterUrl": "https://www.kontenx.net/shows/2600220"
      },
      {
        "descText": "3館 - 關於死亡 죽음에 관하여",
        "theaterUrl": "https://www.kontenx.net/shows/2600217"
      },
      {
        "descText": "4館 - 朴烈 박열",
        "theaterUrl": "https://www.kontenx.net/shows/2600085"
      }
    ],
    "addressEN": "123 Dongsung-gil, Jongno District, Seoul",
    "googleUrl": "https://maps.app.goo.gl/sYQBoiG82phyHctb6",
    "naverUrl": "https://naver.me/Fk73uGGZ",
    "dongKR": "혜화동",
    "dongEN": "Hyehwa-dong"
  },
  {
    "id": "t_10",
    "district": "jongno",
    "nameCN": "T.O.M Theatre",
    "nameKR": "대학로티오엠",
    "lat": 37.582255941944894,
    "lng": 127.00371155926106,
    "categories": ["韓國原創"],
    "hashtags": [],
    "shows": [
      {
        "descText": "1館 - MAD HATTER 매드해터: 미친 모자장수 이야기",
        "theaterUrl": "https://www.kontenx.net/shows/2600074"
      },
      {
        "descText": "2館 - Portrait of a boy 소년의 초상",
        "theaterUrl": "http://www.towntom.com/index.php?mid=theater2&category=307"
      }
    ],
    "addressEN": "85 Daehak-ro 8ga-gil, Jongno District, Seoul",
    "googleUrl": "https://maps.app.goo.gl/6ka1vN3d2bDXimXq9",
    "naverUrl": "https://naver.me/GbDFdkSg",
    "dongKR": "혜화동",
    "dongEN": "Hyehwa-dong"
  },
  {
    "id": "t_11",
    "district": "jongno",
    "nameCN": "NOL 西京廣場 2館",
    "nameKR": "NOL 서경스퀘어",
    "lat": 37.58352407426231,
    "lng": 127.00216659604092,
    "categories": ["韓國原創"],
    "hashtags": [],
    "descText": "晦暗之神 어둑시니",
    "theaterUrl": "https://www.kontenx.net/shows/2600080",
    "addressEN": "148 Dongsung-gil, Jongno District, Seoul",
    "googleUrl": "https://maps.app.goo.gl/JujwE7RPwFGmFWsKA",
    "naverUrl": "https://naver.me/GXApfdL4",
    "dongKR": "혜화동",
    "dongEN": "Hyehwa-dong"
  },
  {
    "id": "t_12",
    "district": "jongno",
    "nameCN": "NOLTheatre 大學路 友利投資證券廳",
    "nameKR": "NOL 씨어터 대학로",
    "lat": 37.58286616973204,
    "lng": 127.00442122487661,
    "categories": ["韓國原創"],
    "hashtags": [],
    "descText": "[1차!] 卡拉馬佐夫兄弟們 브라더스 까라마조프",
    "theaterUrl": "https://www.kontenx.net/shows/2600061",
    "addressEN": "100 Dongsung-gil, Jongno District, Seoul",
    "googleUrl": "https://maps.app.goo.gl/Mo6Km527eHJxnwir9",
    "naverUrl": "https://naver.me/GI3gDi0N",
    "dongKR": "혜화동",
    "dongEN": "Hyehwa-dong"
  },
  {
    "id": "t_13",
    "district": "jongno",
    "nameCN": "Plus Theatre",
    "nameKR": "플러스씨어터",
    "lat": 37.58079067457516,
    "lng": 127.00396046720526,
    "categories": ["韓國原創"],
    "hashtags": [],
    "descText": "星際信使 시데레우스",
    "theaterUrl": "https://www.kontenx.net/shows/2600079",
    "addressEN": "73 Daehak-ro 12-gil, Jongno District, Seoul",
    "googleUrl": "https://maps.app.goo.gl/PVDghr67GLQ2P8pLA",
    "naverUrl": "https://naver.me/xPYjA6wx",
    "dongKR": "혜화동",
    "dongEN": "Hyehwa-dong"
  },
  {
    "id": "t_14",
    "district": "jongno",
    "nameCN": "Yes24 Stage 1館",
    "nameKR": "예스24스테이지",
    "lat": 37.58271116344213,
    "lng": 127.00321334897015,
    "categories": ["韓國原創"],
    "hashtags": [],
    "descText": "해몽가 解夢者",
    "theaterUrl": "https://yes24stage.com/ko/show/detail.php?id=780&P=1&search_obj=&search_str=&type=2&perform_date=20260625",
    "addressEN": "21 Daehak-ro 12-gil, Jongno District, Seoul",
    "googleUrl": "https://maps.app.goo.gl/EbiLYM1jxdFdeepZ6",
    "naverUrl": "https://naver.me/52R55vYZ",
    "dongKR": "혜화동",
    "dongEN": "Hyehwa-dong"
  },
  {
    "id": "t_15",
    "district": "yongsan",
    "nameCN": "Blue Square 友利銀行廳",
    "nameKR": "블루스퀘어",
    "lat": 37.54071160711544,
    "lng": 127.00260488462,
    "categories": ["已購票"],
    "hashtags": [],
    "descText": "伊莉莎白 엘리자벳",
    "theaterUrl": "https://www.kontenx.net/shows/2600224",
    "addressEN": "294 Itaewon-ro, Yongsan District, Seoul",
    "googleUrl": "https://maps.app.goo.gl/o2PhKCWHkLi9yqaN6",
    "naverUrl": "https://naver.me/FDnC47fb",
    "dongKR": "한남동",
    "dongEN": "Hannam-dong"
  },
  {
    "id": "t_16",
    "district": "jung",
    "nameCN": "忠武藝術中心 中劇場 Black",
    "nameKR": "충무아트센터",
    "lat": 37.565964652214646,
    "lng": 127.01486441612285,
    "categories": ["韓國原創"],
    "hashtags": [],
    "descText": "藍花 푸른꽃",
    "theaterUrl": "https://www.kontenx.net/shows/2600227",
    "addressEN": "387 Toegye-ro, Jung District, Seoul",
    "googleUrl": "https://maps.app.goo.gl/SUmvZZ7x6q25m69FA",
    "naverUrl": "https://naver.me/x8tpHeCf",
    "dongKR": "신당동",
    "dongEN": "Sindang-dong"
  },
  {
    "id": "t_17",
    "district": "jongno",
    "nameCN": "et theatre 1",
    "nameKR": "이티 씨어터 원",
    "lat": 37.58707300182262,
    "lng": 126.99976137112074,
    "categories": ["韓國原創"],
    "hashtags": [],
    "descText": "藍旗魚 청새치",
    "theaterUrl": "https://www.kontenx.net/shows/2600098",
    "addressEN": "Seoul, Jongno District, 혜화로 17",
    "googleUrl": "https://maps.app.goo.gl/orZcNVSgoyobQMGu9",
    "naverUrl": "https://naver.me/GvciDSL5",
    "dongKR": "혜화동",
    "dongEN": "Hyehwa-dong"
  },
  {
    "id": "t_18",
    "district": "guro",
    "nameCN": "D-CUBE Link Art Center",
    "nameKR": "디큐브링크아트센터",
    "lat": 37.50901531072758,
    "lng": 126.88960934227119,
    "categories": ["韓國原創"],
    "hashtags": [],
    "descText": "那些日子 그날들",
    "theaterUrl": "https://www.kontenx.net/shows/2600056",
    "addressEN": "662 Gyeongin-ro, Guro District, Seoul",
    "googleUrl": "https://maps.app.goo.gl/u29XSXtWDnuj2RFZ6",
    "naverUrl": "https://naver.me/xeAfl3Ar",
    "dongKR": "신도림동",
    "dongEN": "Sindorim-dong"
  },
  {
    "id": "t_19",
    "district": "gangnam",
    "nameCN": "ARTISTAGE 道谷",
    "nameKR": "아티스테이지 도곡",
    "lat": 37.4874458198479,
    "lng": 127.04713263094864,
    "categories": ["韓國原創"],
    "hashtags": [],
    "descText": "INSIDE THE PLAY：ROULETTE",
    "theaterUrl": "https://www.kontenx.net/shows/2600222",
    "addressEN": "6층, 2753 Nambusunhwan-ro, Gangnam District, Seoul",
    "googleUrl": "https://maps.app.goo.gl/EhPTKwvQ3XqW1paV7",
    "naverUrl": "https://naver.me/GB35PQ8j",
    "dongKR": "도곡1동",
    "dongEN": "Dogok 1(il)-dong"
  },
  {
    "id": "t_20",
    "district": "jongno",
    "nameCN": "NOL Uniplex 1館",
    "nameKR": "NOL 유니플렉스 1관",
    "lat": 37.5811838149866,
    "lng": 127.00367824230227,
    "categories": ["韓國原創"],
    "hashtags": [],
    "descText": "WENTERN STORY 웨스턴 스토리",
    "theaterUrl": "https://www.kontenx.net/shows/2600094",
    "addressEN": "64 Daehak-ro 12-gil, Jongno District, Seoul",
    "googleUrl": "https://maps.app.goo.gl/W3duYXJ9FexRp65V9",
    "naverUrl": "https://naver.me/FqWtD3IZ",
    "dongKR": "혜화동",
    "dongEN": "Hyehwa-dong"
  },
  {
    "id": "t_21",
    "district": "jongno",
    "nameCN": "大學路 SH藝術廳",
    "nameKR": "대학로 SH아트홀",
    "lat": 37.579881713229454,
    "lng": 127.0036118422712,
    "categories": ["韓國原創"],
    "hashtags": [],
    "descText": "奇奇的邊緣性人格障礙日記 키키의 경계성 인격장애 다이어리",
    "theaterUrl": "https://www.kontenx.net/shows/2600221",
    "addressEN": "1-131 Dongsung-dong, Jongno District, Seoul",
    "googleUrl": "https://maps.app.goo.gl/zGPTASNLkgiV47bb9",
    "naverUrl": "https://naver.me/58NXWjqW",
    "dongKR": "혜화동",
    "dongEN": "Hyehwa-dong"
  }
];
