// data.js - Generated from user list

const HOTEL = {
  "lat": 37.5626699,
  "lng": 126.9906379
};

const DISTRICTS = {
  "mapo": {
    "nameCN": "麻浦區",
    "nameKR": "마포구"
  },
  "jongno": {
    "nameCN": "鐘路區",
    "nameKR": "종로구"
  },
  "jung": {
    "nameCN": "中區",
    "nameKR": "중구"
  },
  "yongsan": {
    "nameCN": "龍山區",
    "nameKR": "용산구"
  },
  "gangnam": {
    "nameCN": "江南區",
    "nameKR": "강남구"
  },
  "seongdong": {
    "nameCN": "城東區",
    "nameKR": "성동구"
  },
  "dongdaemun": {
    "nameCN": "東大門區",
    "nameKR": "동대문구"
  },
  "seodaemun": {
    "nameCN": "西大門區",
    "nameKR": "서대문구"
  },
  "seocho": {
    "nameCN": "瑞草區",
    "nameKR": "서초구"
  },
  "yeongdeungpo": {
    "nameCN": "永登浦區",
    "nameKR": "영등포구"
  },
  "eunpyeong": {
    "nameCN": "恩平區",
    "nameKR": "은평구"
  },
  "nowon": {
    "nameCN": "蘆原區",
    "nameKR": "노원구"
  },
  "seongbuk": {
    "nameCN": "城北區",
    "nameKR": "성북구"
  },
  "gwangjin": {
    "nameCN": "廣津區",
    "nameKR": "광진구"
  },
  "songpa": {
    "nameCN": "松坡區",
    "nameKR": "송파구"
  }
};

const CATEGORY_COLORS = {
  "漂亮咖": "var(--cat-cafe)",
  "點心": "var(--cat-snack)",
  "韓式鹹食": "var(--cat-korean)",
  "義大利麵": "var(--cat-pasta)",
  "烤肉": "var(--cat-bbq)",
  "暖暖ㄉ湯": "var(--cat-soup)",
  "湯飯": "var(--cat-gukbap)",
  "麵": "var(--cat-noodle)",
  "HOTEL": "var(--cat-hotel)"
};

const RESTAURANTS = [
  {
    "id": "r_1",
    "district": "seodaemun",
    "nameCN": "日記",
    "nameKR": "일기",
    "lat": 37.5652633080296,
    "lng": 126.92318197854732,
    "category": "漂亮咖",
    "hashtags": [],
    "googleRating": "5.0",
    "googleReviews": "7份",
    "IGreels": "",
    "featuredDish": "法式吐司",
    "addressEN": "18 Seongmisan-ro 29an-gil, Yeonnam-dong, Seoul",
    "dongKR": "연희동",
    "dongEN": "Yeonhui-dong",
    "naverUrl": "https://map.naver.com/p/entry/place/1072280224?placePath=%2Fhome",
    "googleUrl": "https://maps.app.goo.gl/qcx7TZZzVZ2MqsKW6"
  },
  {
    "id": "r_2",
    "district": "mapo",
    "nameCN": "Tis Snack Bar",
    "nameKR": "티스 스낵바",
    "lat": 37.56000611449929,
    "lng": 126.92639656323402,
    "category": "漂亮咖",
    "hashtags": [],
    "googleRating": "4.3",
    "googleReviews": "12份",
    "IGreels": "",
    "featuredDish": null,
    "addressEN": "7 Yeonhui-ro, Donggyo-dong, Mapo-gu, Seoul",
    "dongKR": "연남동",
    "dongEN": "Yeonnam-dong",
    "naverUrl": "https://naver.me/FHlg8V6n",
    "googleUrl": "https://maps.app.goo.gl/2YCd5PGVzKx9wFCV7"
  },
  {
    "id": "r_3",
    "district": "jongno",
    "nameCN": "乙支餃子",
    "nameKR": "을지만두",
    "lat": 37.567799785243054,
    "lng": 127.00816192379439,
    "category": "點心",
    "hashtags": [
      "鳥屎推薦",
      "豆沙包"
    ],
    "googleRating": "4.7",
    "googleReviews": "103份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "18-95 Euljiro 6(yuk)-ga, Jung District, Seoul",
    "dongKR": "종로5·6가동",
    "dongEN": "Jongno5·6Gadong",
    "naverUrl": "https://naver.me/IgJC0bG9",
    "googleUrl": "https://maps.app.goo.gl/njU5cS99CNp7fpTt8"
  },
  {
    "id": "r_4",
    "district": "jongno",
    "nameCN": "Garlic Boy",
    "nameKR": "갈릭보이",
    "lat": 37.57029654438751,
    "lng": 126.99870004874413,
    "category": "點心",
    "hashtags": [
      "廣藏市場",
      "麵包"
    ],
    "googleRating": "4.5",
    "googleReviews": "181份",
    "featuredDish": "大蒜麵包",
    "IGreels": "",
    "addressEN": "88 Changgyeonggung-ro, Jongno District, Seoul",
    "dongKR": "종로1·2·3·4가동",
    "dongEN": "Jongno1·2·3·4Gadong",
    "naverUrl": "https://naver.me/GALWeZId",
    "googleUrl": "https://maps.app.goo.gl/W3HokNVdmZ4s9Qmk6"
  },
  {
    "id": "r_6",
    "district": "jongno",
    "nameCN": "Abebe Bakery",
    "nameKR": "아베베베이커리",
    "lat": 37.56963000154928,
    "lng": 126.99993613470386,
    "category": "點心",
    "hashtags": [
      "廣藏市場",
      "麵包"
    ],
    "googleRating": "4.4",
    "googleReviews": "365份",
    "featuredDish": "濟州島來的奶油餡甜甜圈（口味頗多）、橘子氣泡飲",
    "IGreels": "",
    "addressEN": "201 Cheonggyecheon-ro, Jongno District, Seoul",
    "dongKR": "종로1·2·3·4가동",
    "dongEN": "Jongno1·2·3·4Gadong",
    "naverUrl": "https://naver.me/Fmf6KIKT",
    "googleUrl": "https://maps.app.goo.gl/DbQtUMocZ8zjGPpp8"
  },
  {
    "id": "r_7",
    "district": "jongno",
    "nameCN": "廣藏糖餅",
    "nameKR": "광장호떡",
    "lat": 37.570712825870885,
    "lng": 127.00050463281508,
    "category": "點心",
    "hashtags": [
      "廣藏市場",
      "糖餅"
    ],
    "googleRating": "4.4",
    "googleReviews": "46份",
    "featuredDish": "蜂蜜、紅豆、起司",
    "IGreels": "",
    "addressEN": "206 Jong-ro, Jongno 5(o)-ga, Jongno District, Seoul",
    "dongKR": "종로5·6가동",
    "dongEN": "Jongno5·6Gadong",
    "naverUrl": "https://naver.me/xl0Dyxqh",
    "googleUrl": "https://maps.app.goo.gl/Q3x8Sq4sBiJsnRtLA"
  },
  {
    "id": "r_8",
    "district": "jongno",
    "nameCN": "廣藏市場糯米麻花捲",
    "nameKR": "광장시장 찹쌀꽈배기",
    "lat": 37.570696279743174,
    "lng": 127.00020584217398,
    "category": "點心",
    "hashtags": [
      "廣藏市場",
      "麻花捲"
    ],
    "googleRating": "4.5",
    "googleReviews": "757份",
    "featuredDish": "糯米麻花、紅豆甜甜圈、黑米糯米甜甜圈、紅豆糯米甜甜圈",
    "IGreels": "",
    "addressEN": "Seoul, Jongno District, Jongno 4(sa)-ga, 188 105호",
    "dongKR": "종로1·2·3·4가동",
    "dongEN": "Jongno1·2·3·4Gadong",
    "naverUrl": "https://naver.me/5tJt5fE9",
    "googleUrl": "https://maps.app.goo.gl/RWB73w7MNdHpo7Mz8"
  },
  {
    "id": "r_9",
    "district": "seongdong",
    "nameCN": "自然島鹽可頌",
    "nameKR": "자연도소금빵",
    "lat": 37.54240883178305,
    "lng": 127.05535314769233,
    "category": "點心",
    "hashtags": [
      "麵包"
    ],
    "googleRating": "4.3",
    "googleReviews": "800份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "56-1 Yeonmujang-gil, Seongdong-gu, Seoul",
    "dongKR": "성수2가3동",
    "dongEN": "Seongsu 2(i)-ga 3(sam)-dong",
    "naverUrl": "https://naver.me/xUw1qmBE",
    "googleUrl": "https://maps.app.goo.gl/NWxkVnHBQkBXcMjP9"
  },
  {
    "id": "r_10",
    "district": "mapo",
    "nameCN": "自然島鹽可頌",
    "nameKR": "자연도소금빵",
    "lat": 37.55971179779057,
    "lng": 126.92435372523332,
    "category": "點心",
    "hashtags": [
      "麵包"
    ],
    "googleRating": "4.3",
    "googleReviews": "218份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "Seoul, Mapo-gu, Yanghwa-ro 21-gil, 33 1 층",
    "dongKR": "연남동",
    "dongEN": "Yeonnam-dong",
    "naverUrl": "https://naver.me/xjgchnQq",
    "googleUrl": "https://maps.app.goo.gl/aV4skhkNznWoWsqs9"
  },
  {
    "id": "r_11",
    "district": "seongdong",
    "nameCN": "Hanib Bagel",
    "nameKR": "한입베이글",
    "lat": 37.541446375269956,
    "lng": 127.04626120257495,
    "category": "點心",
    "hashtags": [
      "麵包"
    ],
    "googleRating": "4.7",
    "googleReviews": "86份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "317 Ttukseom-ro, Seongdong-gu, Seoul",
    "dongKR": "성수1가1동",
    "dongEN": "Seongsu1(il)-ga1(il)-dong",
    "naverUrl": "https://naver.me/GFB1Amu6",
    "googleUrl": "https://maps.app.goo.gl/vvvT5J8fgstHgs6t6"
  },
  {
    "id": "r_13",
    "district": "mapo",
    "nameCN": "雨耳樂",
    "nameKR": "우이락 망원본점",
    "lat": 37.556462775781085,
    "lng": 126.90594519964782,
    "category": "點心",
    "hashtags": [
      "望遠市場",
      "炸辣椒"
    ],
    "googleRating": "4.7",
    "googleReviews": "853份",
    "IGreels": "https://www.instagram.com/reel/DVOgpLtj5Y-/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "featuredDish": "辣椒鑲肉（一份三支，原味、起司、甜辣、清湯口味）",
    "addressEN": "22 Poeun-ro 8-gil, Mapo-gu, Seoul",
    "dongKR": "망원2동",
    "dongEN": "Mangwon 2(i)-dong",
    "naverUrl": "https://naver.me/FgHD8wDh",
    "googleUrl": "https://maps.app.goo.gl/1qDmjVNh29sAkvv48"
  },
  {
    "id": "r_14",
    "district": "mapo",
    "nameCN": "勳勳糖餅",
    "nameKR": "훈훈호떡",
    "lat": 37.55593850138689,
    "lng": 126.9063636809724,
    "category": "點心",
    "hashtags": [
      "望遠市場",
      "糖餅"
    ],
    "googleRating": "4.5",
    "googleReviews": "193份",
    "IGreels": "https://www.instagram.com/reel/DVOgpLtj5Y-/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "featuredDish": "原味、起司粉、黃豆粉、Oreo、堅果、冰淇淋口味",
    "addressEN": "25 Poeun-ro 6-gil, Mapo-gu, Seoul",
    "dongKR": "망원2동",
    "dongEN": "Mangwon 2(i)-dong",
    "naverUrl": "https://naver.me/F74V29Yu",
    "googleUrl": "https://maps.app.goo.gl/VJNDTukWhWNmYQwd9"
  },
  {
    "id": "r_15",
    "district": "seongdong",
    "nameCN": "韓貞仙",
    "nameKR": "한정선",
    "lat": 37.54288729937332,
    "lng": 127.0541684849995,
    "category": "點心",
    "hashtags": [
      "大福"
    ],
    "googleRating": "4.4",
    "googleReviews": "301份",
    "IGreels": "",
    "featuredDish": "杜拜巧克力、巧克力草莓、紅豆草莓、艾草紅豆草莓、紅豆奶油、橘子、柿子、奇異果、麝香葡萄、鳳梨口味",
    "addressEN": "Seoul, Seongdong-gu, Yeonmujang-gil, 43 1 1F",
    "dongKR": "성수2가3동",
    "dongEN": "Seongsu 2(i)-ga 3(sam)-dong",
    "naverUrl": "https://naver.me/F9N46G4y",
    "googleUrl": "https://maps.app.goo.gl/45zvnBgxbVrWsynS7"
  },
  {
    "id": "r_16",
    "district": "seongdong",
    "nameCN": "Le Freak",
    "nameKR": "르프리크",
    "lat": 37.54453794817913,
    "lng": 127.0526830592445,
    "category": "點心",
    "hashtags": [
      "漢堡"
    ],
    "googleRating": "4.5",
    "googleReviews": "412份",
    "featuredDish": "炸雞漢堡",
    "IGreels": "",
    "addressEN": "Seoul, Seongdong-gu, Yeonmujang 5-gil, 9-16 B103호",
    "dongKR": "성수1가2동",
    "dongEN": "Seongsu1(il)-ga2(i)-dong",
    "naverUrl": "https://naver.me/GwpMNYi5",
    "googleUrl": "https://maps.app.goo.gl/QixbjBwPqRUs9DsRA"
  },
  {
    "id": "r_17",
    "district": "jung",
    "nameCN": "萬培阿里郎菜包肉",
    "nameKR": "만배아리랑보쌈",
    "lat": 37.54917400626818,
    "lng": 126.86244184613925,
    "category": "韓式鹹食",
    "hashtags": [
      "白切肉"
    ],
    "googleRating": "4.6",
    "googleReviews": "61份",
    "IGreels": "https://www.instagram.com/reel/DXQliiHE2VZ/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "featuredDish": "豬頸背肉泡菜包飯、海鮮蛤蠣刀削麵",
    "addressEN": "17 Deungchon-ro 51-gil, Gangseo-gu, Seoul",
    "dongKR": "등촌2동",
    "dongEN": "Deungchon 2(i)-dong",
    "naverUrl": "https://naver.me/GG7tTMkh",
    "googleUrl": "https://maps.app.goo.gl/YcB3qwxnmxSyJob97"
  },
  {
    "id": "r_18",
    "district": "yongsan",
    "nameCN": "高豆里",
    "nameKR": "고두리",
    "lat": 37.53142959619399,
    "lng": 126.96883337019365,
    "category": "韓式鹹食",
    "hashtags": [
      "豆腐料理"
    ],
    "googleRating": "4.4",
    "googleReviews": "65份",
    "IGreels": "",
    "featuredDish": "芝麻葉豆腐煎餅、辣豆腐湯、泡菜烤五花肉、豆腐鍋",
    "addressEN": "Seoul, Yongsan District, Hangangno 2(i)-ga, 2-39 1층",
    "dongKR": "원효로1동",
    "dongEN": "Wonhyoro1-dong",
    "naverUrl": "https://naver.me/Gj6X2WEN",
    "googleUrl": "https://maps.app.goo.gl/Wh25SX1iDHUfh1WM6"
  },
  {
    "id": "r_19",
    "district": "mapo",
    "nameCN": "QS炸雞",
    "nameKR": "큐스닭강정",
    "lat": 37.55633423473403,
    "lng": 126.90623677945798,
    "category": "韓式鹹食",
    "hashtags": [
      "望遠市場",
      "炸雞"
    ],
    "googleRating": "3.4",
    "googleReviews": "118份",
    "IGreels": "https://www.instagram.com/reel/DVOgpLtj5Y-/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "featuredDish": "",
    "addressEN": "27 Mangwon-ro 8-gil, Mangwon-dong, Mapo-gu, Seoul",
    "dongKR": "망원2동",
    "dongEN": "Mangwon 2(i)-dong",
    "naverUrl": "https://naver.me/5eUc0fjc",
    "googleUrl": "https://maps.app.goo.gl/quzzUH3HXh8AtnZT6"
  },
  {
    "id": "r_20",
    "district": "jongno",
    "nameCN": "元祖裸飯捲",
    "nameKR": "원조누드치즈김밥",
    "lat": 37.570532822281315,
    "lng": 126.99881861506704,
    "category": "韓式鹹食",
    "hashtags": [
      "廣藏市場",
      "飯卷"
    ],
    "googleRating": "4.3",
    "googleReviews": "642份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "41호, 3-2 Changgyeonggung-ro 12-gil, Jongno District, Seoul",
    "dongKR": "종로1·2·3·4가동",
    "dongEN": "Jongno1·2·3·4Gadong",
    "naverUrl": "https://naver.me/xDJucSNM",
    "googleUrl": "https://maps.app.goo.gl/1rkcsQUrCfZ5nQuQ8"
  },
  {
    "id": "r_22",
    "district": "mapo",
    "nameCN": "申美京弘大辣炒雞排",
    "nameKR": "신미경 홍대닭갈비",
    "lat": 37.552353714735695,
    "lng": 126.92188976323828,
    "category": "韓式鹹食",
    "hashtags": [
      "蕭芝芹說一定要吃到的辣炒雞"
    ],
    "googleRating": "4.6",
    "googleReviews": "1618份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "31-10 Wausan-ro 21-gil, Mapo-gu, Seoul",
    "dongKR": "서교동",
    "dongEN": "Seogyo-dong",
    "naverUrl": "https://naver.me/Gubw0jFk",
    "googleUrl": "https://maps.app.goo.gl/GKEh4CGQ4WqPfdKm8"
  },
  {
    "id": "r_23",
    "district": "mapo",
    "nameCN": "韓式馬鈴薯丸湯",
    "nameKR": "옹시미",
    "lat": 37.558829775544446,
    "lng": 126.92207282660203,
    "category": "韓式鹹食",
    "hashtags": [
      "蕎麥煎餅",
      "馬鈴薯疙瘩"
    ],
    "googleRating": "4.8",
    "googleReviews": "79份",
    "IGreels": "https://www.instagram.com/reel/DWgS1xskQFM/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "featuredDish": "",
    "addressEN": "Seoul, Mapo-gu, World Cup buk-ro 4-gil, 59 1층",
    "dongKR": "연남동",
    "dongEN": "Yeonnam-dong",
    "naverUrl": "https://naver.me/xv3DN2qg",
    "googleUrl": "https://maps.app.goo.gl/mxJxER2iPTrQAWqZA"
  },
  {
    "id": "r_24",
    "district": "jung",
    "nameCN": "豬腳小姐",
    "nameKR": "미쓰족발",
    "lat": 37.56480447041299,
    "lng": 126.98343479153587,
    "category": "韓式鹹食",
    "hashtags": [
      "豬腳"
    ],
    "googleRating": "4.4",
    "googleReviews": "1264份",
    "featuredDish": "",
    "IGreels": "https://www.instagram.com/reel/DQy70fmExU-/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "addressEN": "21 Myeongdong 3-gil, Jung District, Seoul",
    "dongKR": "명동",
    "dongEN": "Myeong-dong",
    "naverUrl": "https://naver.me/xv3DIjyN",
    "googleUrl": "https://maps.app.goo.gl/vGJZcKVpbngnKHgL7"
  },
  {
    "id": "r_25",
    "district": "mapo",
    "nameCN": "豬腳小姐",
    "nameKR": "미쓰족발",
    "lat": 37.55583068170859,
    "lng": 126.92366110267096,
    "category": "韓式鹹食",
    "hashtags": [
      "豬腳"
    ],
    "googleRating": "4.3",
    "googleReviews": "1989份",
    "featuredDish": "",
    "IGreels": "https://www.instagram.com/reel/DQy70fmExU-/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "addressEN": "123-1 Eoulmadang-ro, Mapo-gu, Seoul",
    "dongKR": "서교동",
    "dongEN": "Seogyo-dong",
    "naverUrl": "https://naver.me/GubwlgWD",
    "googleUrl": "https://maps.app.goo.gl/4NVDJYZqHBb7pXPx7"
  },
  {
    "id": "r_26",
    "district": "jongno",
    "nameCN": "Solsot Pot Rice",
    "nameKR": "솔솥",
    "lat": 37.57437972166945,
    "lng": 126.99017356672171,
    "category": "韓式鹹食",
    "hashtags": [
      "釜飯"
    ],
    "googleRating": "4.5",
    "googleReviews": "474份",
    "IGreels": "",
    "featuredDish": "牛排、鰻魚",
    "addressEN": "1층, 46 Samil-daero 30-gil, Jongno District, Seoul",
    "dongKR": "가회동",
    "dongEN": "Gahoe-dong",
    "naverUrl": "https://naver.me/FjbnsEfv",
    "googleUrl": "https://maps.app.goo.gl/zLdiWCDsC9Ln5CPH7"
  },
  {
    "id": "r_27",
    "district": "seongbuk",
    "nameCN": "八百家",
    "nameKR": "팔백집",
    "lat": 37.58655069729023,
    "lng": 127.02980144517065,
    "category": "韓式鹹食",
    "hashtags": [
      "排骨"
    ],
    "googleRating": "4.2",
    "googleReviews": "59份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "3 Jongam-ro 27-gil, 고려대 Seongbuk District, Seoul",
    "dongKR": "안암동",
    "dongEN": "Anamdong",
    "naverUrl": "https://naver.me/G1wSXB6K",
    "googleUrl": "https://maps.app.goo.gl/X8M9pWiJEnvx5gKn7"
  },
  {
    "id": "r_28",
    "district": "mapo",
    "nameCN": "Hey George",
    "nameKR": "헤이죠지",
    "lat": 37.561696333045596,
    "lng": 126.92656609845942,
    "category": "義大利麵",
    "hashtags": [],
    "googleRating": "4.9",
    "googleReviews": "291份",
    "IGreels": "https://www.instagram.com/reel/DWBkFyiE9C6/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "featuredDish": "",
    "addressEN": "383-96 Yeonnam-dong, Mapo-gu, Seoul",
    "dongKR": "연남동",
    "dongEN": "Yeonnam-dong",
    "naverUrl": "https://naver.me/GHvqnvW2",
    "googleUrl": "https://maps.app.goo.gl/xXsKiwxEdGZHvyM18"
  },
  {
    "id": "r_29",
    "district": "mapo",
    "nameCN": "HAVE",
    "nameKR": "해브 연남파스타",
    "lat": 37.5618752803497,
    "lng": 126.92605047035961,
    "category": "義大利麵",
    "hashtags": [],
    "googleRating": "4.7",
    "googleReviews": "43份",
    "IGreels": "",
    "featuredDish": "生鮭魚、生牛肉冷義大利麵",
    "addressEN": "55 Yeonhui-ro 1-gil, Mapo-gu, Seoul",
    "dongKR": "연남동",
    "dongEN": "Yeonnam-dong",
    "naverUrl": "https://naver.me/5chutspQ",
    "googleUrl": "https://maps.app.goo.gl/3Ho8kTM728YQ5dFf6"
  },
  {
    "id": "r_30",
    "district": "jung",
    "nameCN": "文化食堂",
    "nameKR": "문화식당",
    "lat": 37.5657210007695,
    "lng": 127.01993758400434,
    "category": "義大利麵",
    "hashtags": [],
    "googleRating": "4.5",
    "googleReviews": "35份",
    "IGreels": "",
    "featuredDish": "蛋包飯、三合一義大利麵",
    "addressEN": "Seoul, Jung District, Sindang-dong, 140-3 2층",
    "dongKR": "황학동",
    "dongEN": "Hwanghak-dong",
    "naverUrl": "https://naver.me/GoD7vP4W",
    "googleUrl": "https://maps.app.goo.gl/wnydzvHpSMATqhH76"
  },
  {
    "id": "r_31",
    "district": "mapo",
    "nameCN": "兔子停",
    "nameKR": "토끼정",
    "lat": 37.55197218154435,
    "lng": 126.9206657690827,
    "category": "義大利麵",
    "hashtags": [],
    "googleRating": "4.3",
    "googleReviews": "269份",
    "IGreels": "https://www.instagram.com/reel/DXBwkXqSq_t/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "featuredDish": "奶油咖哩烏龍麵、炸豬排",
    "addressEN": "13 Jandari-ro 2-gil, Mapo-gu, Seoul",
    "dongKR": "서교동",
    "dongEN": "Seogyo-dong",
    "naverUrl": "https://naver.me/xAFC52uD",
    "googleUrl": "https://maps.app.goo.gl/MZ2pKyuFvmPzhzAP8"
  },
  {
    "id": "r_32",
    "district": "jung",
    "nameCN": "兔子停",
    "nameKR": "토끼정",
    "lat": 37.5553073483632,
    "lng": 126.97102122363017,
    "category": "義大利麵",
    "hashtags": [],
    "googleRating": "3.7",
    "googleReviews": "999份",
    "IGreels": "https://www.instagram.com/reel/DXBwkXqSq_t/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "featuredDish": "奶油咖哩烏龍麵、炸豬排",
    "addressEN": "405 Hangang-daero, Jung District, Seoul",
    "dongKR": "중림동",
    "dongEN": "Jungnim-dong",
    "naverUrl": "https://naver.me/IgJGrH7I",
    "googleUrl": "https://maps.app.goo.gl/9d6ZD83cmPPgokGd7"
  },
  {
    "id": "r_33",
    "district": "mapo",
    "nameCN": "Hotel De GGOODD",
    "nameKR": "오뗄드꾸뜨",
    "lat": 37.56295092968078,
    "lng": 126.92528693833093,
    "category": "義大利麵",
    "hashtags": [],
    "googleRating": "4.7",
    "googleReviews": "318份",
    "IGreels": "",
    "featuredDish": "蜂蜜培根玫瑰醬、法式吐司",
    "addressEN": "Seoul, Mapo-gu, Donggyo-ro 46-gil, 7 101호",
    "dongKR": "연남동",
    "dongEN": "Yeonnam-dong",
    "naverUrl": "https://naver.me/Fr7p5RtM",
    "googleUrl": "https://maps.app.goo.gl/ifjp2xV2Reoyu8pS9"
  },
  {
    "id": "r_34",
    "district": "mapo",
    "nameCN": "十分三文魚",
    "nameKR": "연어롭다",
    "lat": 37.56121742295383,
    "lng": 126.92571412992987,
    "category": "義大利麵",
    "hashtags": [],
    "googleRating": "4.3",
    "googleReviews": "150份",
    "IGreels": "",
    "featuredDish": "鮭魚刺身",
    "addressEN": "42 Donggyo-ro 38-gil, Mapo-gu, Seoul",
    "dongKR": "연남동",
    "dongEN": "Yeonnam-dong",
    "naverUrl": "https://naver.me/G9r5qDkF",
    "googleUrl": "https://maps.app.goo.gl/ie8jg29kZhVj79rD7"
  },
  {
    "id": "r_35",
    "district": "mapo",
    "nameCN": "麻浦牛小腸城",
    "nameKR": "마포곱창타운",
    "lat": 37.55951194234785,
    "lng": 126.92269792610809,
    "category": "烤肉",
    "hashtags": [
      "烤腸"
    ],
    "googleRating": "4.7",
    "googleReviews": "2334份",
    "IGreels": "https://www.instagram.com/reel/DWJhii_kmMQ/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "addressEN": "20 Donggyo-ro 27-gil, Mapo-gu, Seoul",
    "dongKR": "연남동",
    "dongEN": "Yeonnam-dong",
    "naverUrl": "https://naver.me/59voptcA",
    "googleUrl": "https://maps.app.goo.gl/kSGXfZRnHTaZMsLb8"
  },
  {
    "id": "r_36",
    "district": "mapo",
    "nameCN": "天使烤腸",
    "nameKR": "천사곱창",
    "lat": 37.55281129100612,
    "lng": 126.92186511023914,
    "category": "烤肉",
    "hashtags": [
      "烤腸"
    ],
    "googleRating": "4.3",
    "googleReviews": "60份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "36-4 Wausan-ro 21-gil, 서교동 Mapo-gu, Seoul",
    "dongKR": "서교동",
    "dongEN": "Seogyo-dong",
    "naverUrl": "https://map.naver.com/p/entry/place/37801100?placePath=%2Fhome",
    "googleUrl": "https://maps.app.goo.gl/wHU7eQtj2FnsbLEC7"
  },
  {
    "id": "r_37",
    "district": "mapo",
    "nameCN": "第一烤腸",
    "nameKR": "제일곱창",
    "lat": 37.55295855988006,
    "lng": 126.92233182621861,
    "category": "烤肉",
    "hashtags": [
      "烤腸"
    ],
    "googleRating": "4.9",
    "googleReviews": "405份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "Seoul, Mapo-gu, Wausan-ro 21-gil, 28-7 1층",
    "dongKR": "서교동",
    "dongEN": "Seogyo-dong",
    "naverUrl": "https://naver.me/IDFUNqBM",
    "googleUrl": "https://maps.app.goo.gl/GuiPfrY9fPK9Z514A"
  },
  {
    "id": "r_38",
    "district": "gangnam",
    "nameCN": "新沙烤牛腸",
    "nameKR": "신사소곱창",
    "lat": 37.51800331518248,
    "lng": 127.0214520703212,
    "category": "烤肉",
    "hashtags": [
      "烤腸"
    ],
    "googleRating": "4.3",
    "googleReviews": "495份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "62 Apgujeong-ro 2-gil, Gangnam District, Seoul",
    "dongKR": "신사동",
    "dongEN": "Sinsa-dong",
    "naverUrl": "https://naver.me/xucpY7ad",
    "googleUrl": "https://maps.app.goo.gl/7XpPjUUWnJ3cTJ6X9"
  },
  {
    "id": "r_39",
    "district": "mapo",
    "nameCN": "喉嚨水芹菜烤肉",
    "nameKR": "목구멍 홍대입구역점",
    "lat": 37.557077696819455,
    "lng": 126.92058925529835,
    "category": "烤肉",
    "hashtags": [
      "水芹菜"
    ],
    "googleRating": "4.5",
    "googleReviews": "341份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "Seoul, Mapo-gu, World Cup buk-ro 4-gil, 8 1층",
    "dongKR": "연남동",
    "dongEN": "Yeonnam-dong",
    "naverUrl": "https://naver.me/GUwSxgH4",
    "googleUrl": "https://maps.app.goo.gl/TPpm35Jk1eBQVk7U7"
  },
  {
    "id": "r_40",
    "district": "mapo",
    "nameCN": "The Grazing Pig",
    "nameKR": "풀뜯는돼지",
    "lat": 37.561058528933664,
    "lng": 126.92464938879996,
    "category": "烤肉",
    "hashtags": [
      "水芹菜"
    ],
    "googleRating": "4.6",
    "googleReviews": "312份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "Seoul, Mapo-gu, Donggyo-ro 32-gil, 7 1층",
    "dongKR": "연남동",
    "dongEN": "Yeonnam-dong",
    "naverUrl": "https://naver.me/GBFHNoZY",
    "googleUrl": "https://maps.app.goo.gl/bxogfTqMWeLTfC3e7"
  },
  {
    "id": "r_41",
    "district": "yongsan",
    "nameCN": "豬肉店",
    "nameKR": "도야집",
    "lat": 37.53223958160214,
    "lng": 126.97253167234624,
    "category": "烤肉",
    "hashtags": [],
    "googleRating": "4.7",
    "googleReviews": "181份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "27 Hangang-daero 52-gil, Yongsan District, Seoul",
    "dongKR": "한강로동",
    "dongEN": "Hangangnodong",
    "naverUrl": "https://naver.me/GJTiGMwx",
    "googleUrl": "https://maps.app.goo.gl/QuUmyigTZDfdfpX29"
  },
  {
    "id": "r_42",
    "district": "mapo",
    "nameCN": "朝鮮火爐",
    "nameKR": "조선화로구이",
    "lat": 37.5560490561716,
    "lng": 126.92062442072883,
    "category": "烤肉",
    "hashtags": [
      "韓牛"
    ],
    "googleRating": "4.5",
    "googleReviews": "1235份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "351-18 Seogyo-dong, Mapo-gu, Seoul",
    "dongKR": "서교동",
    "dongEN": "Seogyo-dong",
    "naverUrl": "https://naver.me/5JpU0TnJ",
    "googleUrl": "https://maps.app.goo.gl/xFojyCRadtY5bn947"
  },
  {
    "id": "r_43",
    "district": "jung",
    "nameCN": "缽山豬皮",
    "nameKR": "발산껍데기",
    "lat": 37.56029341643286,
    "lng": 126.83710523340443,
    "category": "烤肉",
    "hashtags": [
      "豬皮"
    ],
    "googleRating": "4.2",
    "googleReviews": "80份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "공항대로 269-15 1층 112호, Gangseo-gu, Seoul",
    "dongKR": "가양1동",
    "dongEN": "Gayang 1(il)-dong",
    "naverUrl": "https://naver.me/GipB4rqa",
    "googleUrl": "https://maps.app.goo.gl/9PkSxV3YfARNSxSH7"
  },
  {
    "id": "r_44",
    "district": "mapo",
    "nameCN": "肉夢",
    "nameKR": "맛집 육몽",
    "lat": 37.553600263314785,
    "lng": 126.92059782139611,
    "category": "烤肉",
    "hashtags": [],
    "googleRating": "4.8",
    "googleReviews": "3063份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "19 Yanghwa-ro 16-gil, Mapo-gu, Seoul",
    "dongKR": "서교동",
    "dongEN": "Seogyo-dong",
    "naverUrl": "https://naver.me/FY3yAWtF",
    "googleUrl": "https://maps.app.goo.gl/LJNeFxSD34YUeaZs9"
  },
  {
    "id": "r_45",
    "district": "seongdong",
    "nameCN": "黨燒肉",
    "nameKR": "꿉당",
    "lat": 37.54324343284116,
    "lng": 127.05756144714864,
    "category": "烤肉",
    "hashtags": [
      "黨燒肉"
    ],
    "googleRating": "4.5",
    "googleReviews": "449份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "Seoul, Seongdong-gu, Seongsui-ro 20-gil, 10 경협회관 104호",
    "dongKR": "성수2가3동",
    "dongEN": "Seongsu 2(i)-ga 3(sam)-dong",
    "naverUrl": "https://naver.me/FZ275oxv",
    "googleUrl": "https://maps.app.goo.gl/eGNPJ8WD931LjteY6"
  },
  {
    "id": "r_46",
    "district": "seocho",
    "nameCN": "黨燒肉",
    "nameKR": "꿉당",
    "lat": 37.516848649162775,
    "lng": 127.01908852436736,
    "category": "烤肉",
    "hashtags": [
      "黨燒肉"
    ],
    "googleRating": "4.4",
    "googleReviews": "769份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "615 Gangnam-daero, Seocho District, Seoul",
    "dongKR": "잠원동",
    "dongEN": "Jamwon-dong",
    "naverUrl": "https://naver.me/5uIYjvee",
    "googleUrl": "https://maps.app.goo.gl/c6ErZdNr2ZSEUTMv8"
  },
  {
    "id": "r_47",
    "district": "seongdong",
    "nameCN": "祖傳三代馬鈴薯排骨湯",
    "nameKR": "소문난 성수 감자탕",
    "lat": 37.5430457083058,
    "lng": 127.05438584606846,
    "category": "暖暖ㄉ湯",
    "hashtags": [
      "馬鈴薯排骨湯"
    ],
    "googleRating": "4.1",
    "googleReviews": "6035份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "45 Yeonmujang-gil, Seongdong-gu, Seoul",
    "dongKR": "성수2가3동",
    "dongEN": "Seongsu 2(i)-ga 3(sam)-dong",
    "naverUrl": "https://naver.me/GgWkGs9y",
    "googleUrl": "https://maps.app.goo.gl/pcuNTtNQERyY4BYRA"
  },
  {
    "id": "r_48",
    "district": "mapo",
    "nameCN": "百年土種蔘鷄湯",
    "nameKR": "백년토종삼계탕",
    "lat": 37.554471739672366,
    "lng": 126.92022646413989,
    "category": "暖暖ㄉ湯",
    "hashtags": [
      "人蔘雞湯"
    ],
    "googleRating": "4.2",
    "googleReviews": "1921份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "118 Yanghwa-ro, Mapo-gu, Seoul",
    "dongKR": "서교동",
    "dongEN": "Seogyo-dong",
    "naverUrl": "https://naver.me/53lKjV6q",
    "googleUrl": "https://maps.app.goo.gl/HpVQmDBfZC1JJbvL7"
  },
  {
    "id": "r_49",
    "district": "mapo",
    "nameCN": "光雞",
    "nameKR": "광계",
    "lat": 37.56177028796768,
    "lng": 126.92631117840976,
    "category": "暖暖ㄉ湯",
    "hashtags": [
      "人蔘雞湯"
    ],
    "googleRating": "4.8",
    "googleReviews": "25份",
    "IGreels": "https://www.instagram.com/reel/DWLiWlmEYTS/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "featuredDish": "",
    "addressEN": "Seoul, Mapo-gu, Yeonnam-dong, 383-72 1.5층",
    "dongKR": "연남동",
    "dongEN": "Yeonnam-dong",
    "naverUrl": "https://naver.me/FgTz17PI",
    "googleUrl": "https://maps.app.goo.gl/ScX3zgs8BmunzBFg6"
  },
  {
    "id": "r_50",
    "district": "mapo",
    "nameCN": "崔社長家的雞",
    "nameKR": "최사장네닭",
    "lat": 37.56072629367486,
    "lng": 126.9237654935975,
    "category": "暖暖ㄉ湯",
    "hashtags": [
      "辣燉雞湯"
    ],
    "googleRating": "4.0",
    "googleReviews": "263份",
    "IGreels": "https://www.instagram.com/reel/DYgYyRYSJyc/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "featuredDish": "",
    "addressEN": "4-1 Yeonnam-ro, Mapo-gu, Seoul",
    "dongKR": "연남동",
    "dongEN": "Yeonnam-dong",
    "naverUrl": "https://naver.me/xWTnmRpq",
    "googleUrl": "https://maps.app.goo.gl/RhGDEncxyc1gjAn7A"
  },
  {
    "id": "r_51",
    "district": "jongno",
    "nameCN": "HOISIK",
    "nameKR": "호이식",
    "lat": 37.578281392104785,
    "lng": 126.98627126071804,
    "category": "暖暖ㄉ湯",
    "hashtags": [
      "一隻雞"
    ],
    "googleRating": "4.7",
    "googleReviews": "57份",
    "IGreels": "https://www.instagram.com/reel/DVayjKqk4kN/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "featuredDish": "",
    "addressEN": "Seoul, Jongno District, Bukchon-ro 2-gil, 10 1층",
    "dongKR": "가회동",
    "dongEN": "Gahoe-dong",
    "naverUrl": "https://naver.me/5r3E0IpQ",
    "googleUrl": "https://maps.app.goo.gl/6JTsFEwkrRkVEn617"
  },
  {
    "id": "r_52",
    "district": "jongno",
    "nameCN": "李福姬解酒湯",
    "nameKR": "이복희해장",
    "lat": 37.56941897451093,
    "lng": 126.98734439388396,
    "category": "暖暖ㄉ湯",
    "hashtags": [
      "解酒湯"
    ],
    "googleRating": "4.1",
    "googleReviews": "16份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "Seoul, Jongno District, Samil-daero, 385 이복희해장 1층, 2층",
    "dongKR": "종로1·2·3·4가동",
    "dongEN": "Jongno1·2·3·4Gadong",
    "naverUrl": "https://naver.me/5yWRkr3V",
    "googleUrl": "https://maps.app.goo.gl/BWMnH6TGkusEXe7n9"
  },
  {
    "id": "r_53",
    "district": "seongdong",
    "nameCN": "實費屋",
    "nameKR": "실비옥",
    "lat": 37.54385251524655,
    "lng": 127.05827977710037,
    "category": "暖暖ㄉ湯",
    "hashtags": [
      "牛肉海帶鍋"
    ],
    "googleRating": "4.1",
    "googleReviews": "21份",
    "featuredDish": "",
    "IGreels": "https://www.instagram.com/reel/DU5nQ7eEeZR/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "addressEN": "126 Achasan-ro, Seongdong-gu, Seoul",
    "dongKR": "성수2가3동",
    "dongEN": "Seongsu 2(i)-ga 3(sam)-dong",
    "naverUrl": "https://naver.me/GEXUrqqw",
    "googleUrl": "https://maps.app.goo.gl/ECTZ5W5x6KVahWkD6"
  },
  {
    "id": "r_54",
    "district": "jung",
    "nameCN": "保承會館",
    "nameKR": "보승회관",
    "lat": 37.56469137039903,
    "lng": 126.98479766189318,
    "category": "湯飯",
    "hashtags": [],
    "googleRating": "3.6",
    "googleReviews": "136份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "13 Myeongdong 9-gil, Jung District, Seoul",
    "dongKR": "명동",
    "dongEN": "Myeong-dong",
    "naverUrl": "https://naver.me/FfeYK0QT",
    "googleUrl": "https://maps.app.goo.gl/uZ8KizqGuHsoAJbw9"
  },
  {
    "id": "r_55",
    "district": "seodaemun",
    "nameCN": "保承會館",
    "nameKR": "보승회관",
    "lat": 37.556711016411484,
    "lng": 126.92883223394712,
    "category": "湯飯",
    "hashtags": [],
    "googleRating": "4.0",
    "googleReviews": "460份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "131 Eoulmadang-ro, Mapo-gu, Seoul",
    "dongKR": "서교동",
    "dongEN": "Seogyo-dong",
    "naverUrl": "https://naver.me/5hua5O6V",
    "googleUrl": "https://maps.app.goo.gl/ofUeBpq2YVf4pUdv8"
  },
  {
    "id": "r_56",
    "district": "jung",
    "nameCN": "河東津",
    "nameKR": "하동진",
    "lat": 37.566193664499615,
    "lng": 127.01594020597531,
    "category": "湯飯",
    "hashtags": [
      "白切肉"
    ],
    "googleRating": "4.3",
    "googleReviews": "365份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "112 Heungin-dong, Jung District, Seoul",
    "dongKR": "신당동",
    "dongEN": "Sindang-dong",
    "naverUrl": "https://naver.me/5mI0v3oy",
    "googleUrl": "https://maps.app.goo.gl/yQtUb1JLcF2dTm579"
  },
  {
    "id": "r_57",
    "district": "seongdong",
    "nameCN": "豚骨藥房",
    "nameKR": "돈골약방",
    "lat": 37.54545144642206,
    "lng": 127.05145933281165,
    "category": "湯飯",
    "hashtags": [],
    "googleRating": "4.9",
    "googleReviews": "80份",
    "IGreels": "https://www.instagram.com/reel/DYrBH8dyqSe/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "featuredDish": "",
    "addressEN": "Seoul, Seongdong-gu, Seongsuil-ro 8-gil, 28 1 층",
    "dongKR": "성수1가2동",
    "dongEN": "Seongsu1(il)-ga2(i)-dong",
    "naverUrl": "https://naver.me/GEXhVhza",
    "googleUrl": "https://maps.app.goo.gl/RyJb4Ebtcuw6BV2W9"
  },
  {
    "id": "r_58",
    "district": "jung",
    "nameCN": "正雅閣",
    "nameKR": "정아각",
    "lat": 37.64200573234901,
    "lng": 127.02476431495127,
    "category": "麵",
    "hashtags": [
      "炸醬麵"
    ],
    "googleRating": "4.3",
    "googleReviews": "60份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "1064 Hancheon-ro, Suyu-dong, Gangbuk-gu, Seoul",
    "dongKR": "수유2동",
    "dongEN": "Suyu 2(i)-dong",
    "naverUrl": "https://naver.me/502MeDkZ",
    "googleUrl": "https://maps.app.goo.gl/NoN42cFC1nCo1hjA9"
  },
  {
    "id": "r_59",
    "district": "mapo",
    "nameCN": "棒槌手工刀削麵",
    "nameKR": "",
    "lat": 37.55650575159846,
    "lng": 126.90689462815595,
    "category": "麵",
    "hashtags": [
      "望遠市場",
      "刀削麵"
    ],
    "googleRating": "4.2",
    "googleReviews": "353份",
    "IGreels": "https://www.instagram.com/reel/DUdMPfEjPSy/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==",
    "featuredDish": "",
    "addressEN": "414-26 망원제1동 Mapo-gu, Seoul",
    "dongKR": "망원2동",
    "dongEN": "Mangwon 2(i)-dong",
    "naverUrl": "https://naver.me/xv3DRVNF",
    "googleUrl": "https://maps.app.goo.gl/XW68RDME2CgpUmYT8"
  },
  {
    "id": "r_60",
    "district": "seongdong",
    "nameCN": "熊甲刀削麵",
    "nameKR": "웅칼",
    "lat": 37.545067662672174,
    "lng": 127.05424101856917,
    "category": "麵",
    "hashtags": [
      "刀削麵"
    ],
    "googleRating": "4.9",
    "googleReviews": "193份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "1F Seongdong-gu, Seongsu-dong 2(i)-ga, Achasan-ro, 92",
    "dongKR": "성수2가3동",
    "dongEN": "Seongsu 2(i)-ga 3(sam)-dong",
    "naverUrl": "https://naver.me/GcKx1wIb",
    "googleUrl": "https://maps.app.goo.gl/f71tYBxru4xTdqqm8"
  },
  {
    "id": "r_61",
    "district": "jongno",
    "nameCN": "南浦麵屋",
    "nameKR": "남포면옥",
    "lat": 37.56763265353615,
    "lng": 126.98183606824426,
    "category": "麵",
    "hashtags": [
      "冷麵"
    ],
    "googleRating": "3.8",
    "googleReviews": "2266份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "24 Eulji-ro 3-gil, Jung District, Seoul",
    "dongKR": "종로1·2·3·4가동",
    "dongEN": "Jongno1·2·3·4Gadong",
    "naverUrl": "https://naver.me/FeXRk4zh",
    "googleUrl": "https://maps.app.goo.gl/TaynxDh59wBS9TXr9"
  },
  {
    "id": "r_62",
    "district": "jongno",
    "nameCN": "乙密臺平壤冷麵",
    "nameKR": "을밀대",
    "lat": 37.567373065273685,
    "lng": 126.9800304015735,
    "category": "麵",
    "hashtags": [
      "冷麵"
    ],
    "googleRating": "4.1",
    "googleReviews": "253份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "40 B1 Namdaemun-ro 9-gil, Jung District, Seoul",
    "dongKR": "종로1·2·3·4가동",
    "dongEN": "Jongno1·2·3·4Gadong",
    "naverUrl": "https://naver.me/xrSQd4FI",
    "googleUrl": "https://maps.app.goo.gl/bSNEYm71eNAfw2Qj7"
  },
  {
    "id": "r_63",
    "district": "gangnam",
    "nameCN": "乙密臺平壤冷麵",
    "nameKR": "을밀대",
    "lat": 37.49558831128396,
    "lng": 127.03050931465313,
    "category": "麵",
    "hashtags": [
      "冷麵"
    ],
    "googleRating": "4.0",
    "googleReviews": "1442份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "46 Teheran-ro 4-gil, Gangnam District, Seoul",
    "dongKR": "역삼1동",
    "dongEN": "Yeoksam 1(il)-dong",
    "naverUrl": "https://naver.me/GYC97lmL",
    "googleUrl": "https://maps.app.goo.gl/rPV8ZdhQsdSxpNZv5"
  },
  {
    "id": "r_64",
    "district": "gangnam",
    "nameCN": "新沙煎餅",
    "nameKR": "신사전",
    "lat": 37.51884931162439,
    "lng": 127.02304408715368,
    "category": "韓式鹹食",
    "hashtags": [
      "煎餅"
    ],
    "googleRating": "4.0",
    "googleReviews": "514份",
    "IGreels": "",
    "featuredDish": "",
    "addressEN": "18 Dosan-daero 11-gil, Gangnam District, Seoul",
    "dongKR": "신사동",
    "dongEN": "Sinsa-dong",
    "naverUrl": "https://naver.me/5D8tuw8q",
    "googleUrl": "https://maps.app.goo.gl/tE678JgnK2fSfhYcA"
  },
  {
    "id": "r_65",
    "district": "mapo",
    "nameCN": "Musoe泡菜五花肉",
    "nameKR": "무쇠김치삼겹",
    "lat": 37.552857615564534,
    "lng": 126.92266826736592,
    "category": "烤肉",
    "hashtags": [
      "烤腸"
    ],
    "googleRating": "4.6",
    "googleReviews": "263份",
    "featuredDish": "",
    "IGreels": "https://www.instagram.com/reel/DUc-yZ-Ep6W/?utm_source=ig_web_copy_link&igsh=NTc4MTIwNjQ2YQ==",
    "addressEN": "20-5 Wausan-ro 21-gil, Seogyo-dong, Mapo-gu, Seoul",
    "dongKR": "서교동",
    "dongEN": "Seogyo-dong",
    "naverUrl": "https://naver.me/5vcHkgA4",
    "googleUrl": "https://maps.app.goo.gl/u6fon2Hd4DzTUy7A7"
  },
  {
    "id": "r_66",
    "district": "jung",
    "nameCN": "Musoe泡菜五花肉",
    "nameKR": "무쇠김치삼겹",
    "lat": 37.56196141283083,
    "lng": 126.98537061349127,
    "category": "烤肉",
    "hashtags": [
      "烤腸"
    ],
    "googleRating": "4.8",
    "googleReviews": "988份",
    "featuredDish": "",
    "IGreels": "https://www.instagram.com/reel/DUc-yZ-Ep6W/?utm_source=ig_web_copy_link&igsh=NTc4MTIwNjQ2YQ==",
    "addressEN": "Seoul, Jung District, Myeongdong 8ga-gil, 7 2층",
    "dongKR": "명동",
    "dongEN": "Myeong-dong",
    "naverUrl": "https://naver.me/FqWta5qP",
    "googleUrl": "https://maps.app.goo.gl/uYHUuBScu5SBRJ7Z8"
  },
  {
    "id": "r_67",
    "district": "seongdong",
    "nameCN": "朝朝刀削麵",
    "nameKR": "조조칼국수",
    "lat": 37.54546414325718,
    "lng": 127.0570752631429,
    "category": "麵",
    "hashtags": [
      "蕭芝芹說一定要吃到的蛤蜊刀削麵"
    ],
    "googleRating": "4.5",
    "googleReviews": "406份",
    "featuredDish": "",
    "IGreels": "",
    "addressEN": "Seoul, Seongdong-gu, Seongsuil-ro 8-gil, 55 1 층",
    "dongKR": "성수2가3동",
    "dongEN": "Seongsu 2(i)-ga 3(sam)-dong",
    "naverUrl": "https://naver.me/xoH8fSpV",
    "googleUrl": "https://maps.app.goo.gl/qEovCWp8GQdQgLGE6"
  }
];
